### ISSUE TITLE
get large amount of data, need :limit?

### ISSUE THREAD

**Issue by bl4d3** [arsduo/koala#105]
Hi,
I'm trying to get my friends picture in this way
  <% @friends = @graph.get_connections('me', 'friends')%>
    <% @friends.each do |friend| %>
    <%= image_tag @graph.get_picture(friend['id']) %>
  <% end %>
as you can figure out if I have 1000friends its pretty impossibile to retrieve all them in a short time, is there a way to get just first 10, for example, friends?
Which is the best approach to this?
Thanks

**Comment by Meekohi** [comment]
Syntax is a little weird in some cases. In case it helps anyone else, this works:
`@graph.get_object(self.facebook_uid, {fields: [:name,"events.limit(500){id,place,description,category}"]})`
