### ISSUE TITLE
Koala with sinatra

### ISSUE THREAD

**Issue by dayanand-sourcebits** [arsduo/koala#128]
Hey iam a fairly new ruby newbie so could you please help me how to do this part in sinatra? 

<%= link_to 'Previous', url_for(:page => @results.previous_page_params) %>
<%= link_to 'Next', url_for(:page => @results.next_page_params) %>

The example is only for rails iam not able to get this thing working for  sinatra. Thanks

**Comment by dmilisic** [comment]
This [wiki page](https://github.com/arsduo/koala/wiki/Graph-API) still links here. However this code doesn't work any more (with new koala). The controller code should look like this:

```ruby
def index
  # get the first page, or a next/previous page if appropriate params are sent
  if url = params[:pageURL]
    # use GraphCollection's method to get Koala-friendly params from the Facebook URL
    url_params = Koala::Facebook::API::GraphCollection.parse_page_url(url)
    # then use those params to get the next page
    results = your_graph_api_object.get_page(url_params)
  else
    # get the first page of results as usual
  end
end
```
