### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed 

### ISSUE THREAD

**Issue by alexandergiraldo** [arsduo/koala#130]
Hi There,

I'm having this problem with Koala 1.2, yesterday I updated Koala 1.0.0 to Koala 1.2, also updated the javascript sdk:

FB.init({
    appId  : $('#fb-app').data('appId'),
    status : true, // check login status
    cookie : true, // enable cookies to allow the server to access the session
    xfbml  : true,  // parse XFBML
    oauth  : true});

My facebook app:

Remove Deprecated APIs: enable
Stream post URL security: disable
signed_request for Canvas: enable
Timezone-less events: enable
Upgrade to Requests 2.0: enable
iframe Page Tab: enable
Require manage_notifications: enable
Forces use of login secret for OAuth call and for auth.login: enable
Encrypted Access Token: enable
Enhanced Auth Dialog: enable
page_hours: disable

When I try this:

oauth = Koala::Facebook::OAuth.new(Facebook::APP_ID, Facebook::SECRET)
oauth.get_user_info_from_cookies(cookies)

Somethig is wrong, and I get:

OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed 

Thanks for your Help

**Comment by udit7590** [comment]
I encountered the same problem. I was configuring the Koala wrong. In the graph_server setting, I mistakenly mentioned my own server address. Here is the correct one:

Koala.configure do |config|
  config.graph_server = 'graph.facebook.com'
end
