### ISSUE TITLE
Expired cookies

### ISSUE THREAD

**Issue by icambron** [arsduo/koala#156]
I'm using `get_user_info_from_cookies`. The docs say:

```
Of course, if the cookies aren't valid (expired, falsified, etc.) the method will simply return nil.
```

But I'm getting this:

```
Koala::Facebook::APIError - OAuthException: Code was invalid or expired. Session has expired at unix time 1324044000. The current unix time is 1324300957.:
```

I can wrap it with a begin/rescue, but it feels like a bug.

**Comment by davidalejandroaguilar** [comment]
Uh, `get_user_info_from_cookies(cookies)` is actually raising `Koala::Facebook::OAuthTokenRequestError` for me on Koala 3.0 on a `fbsr_` expired cookie.
