### ISSUE TITLE
How to perform Page posts?

### ISSUE THREAD

**Issue by ylluminate** [arsduo/koala#186]
Hitherto I've been banging my head against a wall in an attempt to post some automated event updates to our corporate Facebook Page via the `fb_graph` gem.  It seems as though it should be straight forward as I explain here: http://stackoverflow.com/questions/10180170/how-to-post-facebook-page-updates-using-ruby-fb-graph

How would this be accomplishable via `koala`?  Could you share some details here as to the steps to take in order to get this working?

**Comment by billba** [comment]
I'm having this exact problem as @sfeu - I'm making public posts as the page admin, but they are only visible to me.

**Comment by kurko** [comment]
For future reference, it has to be `publish_pages` now, **NOT** `publish_stream`.
