### ISSUE TITLE
HTTP 502 when trying #put_picture

### ISSUE THREAD

**Issue by archit** [arsduo/koala#215]
So I started with a simple sinatra application, via which I'm trying to upload a picture from my controller's action to facebook. In particular I started with the template app provided by Heroku. Relevant versions are

Ruby 1.9.3-p125
Sinatra 1.2.6
Koala 1.4.0

As a test for my overall setup, when I do a `#put_wall_post()` call, the post appears fine on my facebook wall. 

What I'm trying to achieve is that in my sinatra action I get a uploaded file and I forward the upload to my facebook wall. This is my action in sinatra

```
post '/upload' do
  @graph  = Koala::Facebook::API.new(session[:access_token])

  # Forward image to facebook
  response = @graph.put_picture(params['upload_file'])

  # Redirect back to home
  redirect '/'
end
```

`upload_file` is the file_hash ofcourse. I have verified that correctly.

When the post happens, the action hangs on the `#put_picture` call and after (what I assume is 60 seconds) timeout, returns the error

```
HTTP 502: Response body: Got EOF while waiting for outstanding responses
```

Any ideas/suggestions for debugging this would be welcome.

**Comment by arsduo** [comment]
Apologies for never getting back to this. I'm assuming we all figured this out a long, long time ago. (Definitely reopen if not.)
