### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by ryanb** [arsduo/koala#226]
Since both OAuth and RealtimeUpdates require the `app_id` and `secret` would you consider providing a central configuration where one can set this globally? This would remove the need for [the solution presented here](https://github.com/arsduo/koala/wiki/Koala-on-Rails) which isn't very pretty. Perhaps something similar to the Twitter gem:

```
Koala.configure do |config|
  config.app_id = APP_ID
  config.secret = APP_SECRET
end
```

You might also want to look at the ENV variables and have them default to those values: `ENV["FACEBOOK_APP_ID"]` for example.

**Comment by arsduo** [comment]
So it's been quite a while, but this is still an open and interesting issue. I'm tagging this for consideration for a future release. Thanks for the suggestion.

**Comment by arsduo** [comment]
(If you or anyone reading this wants to submit a PR I'd be glad to review it!)

**Comment by arsduo** [comment]
Good news! I'm about to merge #591, which adds global configuration for all the various attributes the gem uses.
