### ISSUE TITLE
NameError: undefined local variable or method `cookies' for main:Object

### ISSUE THREAD

**Issue by nabil-takla** [arsduo/koala#236]
This is a web app that uses FB connect. Koala - Rails

Controller code:

class UsersController < ApplicationController
before_filter :parse_facebook_cookies

def parse_facebook_cookies
  @facebook_cookies ||= Koala::Facebook::OAuth.new('api_id','app_secret').get_user_info_from_cookie(cookies)
end

def index
  @users = User.all
end

def show
 @user = User.find(params[:id])
end

def new
  @user = User.new
  @title = "sign up"
  require 'koala'

  @graph = Koala::Facebook::API.new
  @access_token = @facebook_cookies["access_token"]

  @user1 = @graph.get_object("me")
  @user.name = @user1["name"]
  @user.uid = @user1["id"]
  @user.save
end
end

At the console:
@oauth = Koala::Facebook::OAuth.new(api_id, app_secret) --- executes OK
BUT  @oauth.get_user_info_from_cookie(cookies) ---- gives me the following error:
NameError: undefined local variable or method `cookies' for main:Object

**Comment by alslp** [comment]
Hi Nabil, I got the same problem here. 
Can you specify what's the problem with the setup for koala?
