### ISSUE TITLE
ref attribute not getting registered in Facebook Insights

### ISSUE THREAD

**Issue by kristallizer** [arsduo/koala#239]
I am using the `put_wall_post` call to create notifications on Facebook walls of an authenticated user's friends. I am also sending a 'ref' attribute in the `attachment` hash which is the second argument to the call, as documented [here](http://rubydoc.info/github/arsduo/koala/master/Koala/Facebook/GraphAPIMethods#put_wall_post-instance_method).

The `attachment` hash looks something like this:

``` json
{
  "message"=>"Some random message", 
  "name"=>"Some random name", 
  "description"=>"Some random description", 
  "picture"=>"http://someurl.com/images/some_feed_icon.png", 
  "ref"=>"some_ref"
}
```

But this isn't working - I am not able to see `some_ref` as a Story Type in the Insights dashboard. Any ideas?

**Comment by arsduo** [comment]
`put_wall_post` should have done basically that, so that's strange. I'm guessing this is no longer an active issue (sorry about the crazy late response), so I'm going to close it, but please feel free to reopen it if it's still a problem.
