### ISSUE TITLE
Koala::Facebook::APIError when trying to publish to a user's stream. 

### ISSUE THREAD

**Issue by darokel** [arsduo/koala#251]
Hi, 

I've followed  this railscast http://railscasts.com/episodes/363-facebook-open-graph in order to integrate FB into my Rails app. When I try to test out publishing to a users stream from Terminal, I keep getting the following error: 

<code>
u = User.last
  User details... with oauth token etc> 
</code>

<code>
u.facebook.put_connections("me", "ramenhut:review", anime:  url)
</code>

Keeps throwing:

<code>
Koala::Facebook::APIError: HTTP 500: Response body: {"error":{"message":"An unexpected error has occurred. Please retry your request later.","type":"OAuthException","code":2}}
</code>

This used to work fine before, however, I re-created my rails app to use Devise for authentication as I made one from scratch with the previous version. Since I've re-create this functionality into my new rails app, I keep getting the error above. I DID also try to test out the functionality in my old app just to make sure it had nothing to do with the app itself but I was still getting the error. 

I've configured all the Open Graph settings correctly on my Facebook App.

Could anyone help?

**Comment by arsduo** [comment]
I'm guessing this is no longer an active issue (sorry about the crazy late response), so I'm going to close it, but please feel free to reopen it if it's still a problem. 500 errors mean something went wrong on Facebook's side and usually that goes away once they fix the bug.
