### ISSUE TITLE
How Can i share a post using the post id

### ISSUE THREAD

**Issue by metripurari** [arsduo/koala#270]
I am using Koala gem and in my UI i have an share link. How can i share the posts using the post id. Can it be done like this.

```
    @facebook = FacebookToken.first
    @graph = Koala::Facebook::API.new(@facebook.access_token)
    @graph.put_object(params[:post_id], "share",:message => "First!")
```

It gives the following error

```
     Koala::Facebook::ClientError: type: OAuthException, code: 240, message: (#240) Requires a valid user is specified (either via the session or via the API parameter for specifying the user. [HTTP 403]
```

I thing something going wrong with permission. I have added the following permission in the fave bool app

```
    "share_item,manage_pages,publish_stream,read_stream,offline_access,create_event,read_insights, manage_notifications"
```

Do I need to some other permission to share a post using post id

**Comment by danielbonnell** [comment]
Hello!

I'm having the same issue. I want to be able to share a post on my timeline through the API given the original post's id. I've tried something like this, but I get an error message. Additionally I can't locate any documentation on how to accomplish this.

Thanks!

Here's what I tried:

```
client.put_connections(pid, 'shares', message: 'This is a test share')
```

Here's the error I'm getting:

```
Koala::Facebook::ClientError: type: GraphMethodException, code: 100, message: Unsupported post request. Object with ID '10153649843290070_10154808445385070' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api [HTTP 400]
from /Users/ACIDSTEALTH/.gem/ruby/2.3.0/gems/koala-2.2.0/lib/koala/api/graph_api.rb:515:in `block in graph_call'
```

**Comment by rodrigotavio91** [comment]
I've found a work around for this issue, for anyone who are facing the same problem. Just publish the post link on user's wall:

`client.put_wall_post('foo', link: "https://www.facebook.com/{page_id}/posts/{post_id}")`

Of course, your app must require the `publish_actions` permission from user.

This worked for me. 

In my case, I was trying to share a post from a page. I guess you can achieve the same if you want to share a post from a user, just changing the `page_id` for the user's id.
