### ISSUE TITLE
Koala::Facebook::APIError when grabbing friends checkins

### ISSUE THREAD

**Issue by shuma** [arsduo/koala#276]
So can I use koala for grabbing friends checkins. 
I tried this in the console:

u.facebook.get_connections("me","friends", :fields => "checkins.")

but I got this error all the time:

Koala::Facebook::APIError: HTTP 500: Response body: {"error_code":1,"error_msg":"An unknown error occurred"}

Does koala provide functions for getting checkins form users friends?

**Comment by arsduo** [comment]
I'm guessing this is no longer an active issue (sorry about the crazy late response), so I'm going to close it, but please feel free to reopen it if it's still a problem. 500 errors mean something went wrong on Facebook's side and usually that goes away once they fix the bug.
