### ISSUE TITLE
Privacy must be JSONified before posting to Facebook

### ISSUE THREAD

**Issue by avk** [arsduo/koala#291]
I've been successfully posting a custom action via the Open Graph API with custom privacy settings for the last month or so. The privacy settings were working until recently, which may have to something to do with [Facebook's February 2013 breaking changes](https://developers.facebook.com/roadmap/completed-changes/#february-2013), though nothing privacy-specific is listed there. 

An example of my old, working code:

``` ruby
# method on a model with attributes for things like facebook privacy, facebook user IDs, and a facebook message
def submit(invite_url)
  privacy = if self.facebook_privacy == "CUSTOM"
    { "value" => "CUSTOM", "allow" => self.facebook_ids.join(",") }
  else
    { "value" => self.facebook_privacy }
  end
  graph = Koala::Facebook::API.new(self.sender.facebook_token)
  graph.put_connections("me", "#{ FACEBOOK_NAMESPACE }:send", 
    :invite => invite_url,
    :message => self.facebook_message,
    :privacy => privacy)
end
```

I had to change `privacy` to `privacy.to_json` in the `put_connections` arguments to get Facebook to respect my privacy parameter. 

Should this `to_json` call be Koala's responsibility? I don't see any specific handling of privacy in the current implementation of `put_connections` or any of it's helpers.

**Comment by arsduo** [comment]
Apologies for never getting back to this. Are you still encountering these issues? How did you work around it?

**Comment by arsduo** [comment]
I'm going to close the issue since it's  been a while; please reopen it if you are still having a problem with the gem or open a new one if needed. Thanks for using Koala!
