### ISSUE TITLE
Add notifications support

### ISSUE THREAD

**Issue by gfeil** [arsduo/koala#297]
I noticed there isn't any support for app notifications in the gem:
https://developers.facebook.com/docs/howtos/notifications-api/

This would be a nice addition to the gem. Unless I'm not aware that this is already done or in progress, I will fork and add, and send a pull request.

**Comment by ssoulless** [comment]
@jatinganhotra You saved my life!!! amazing now it works wonderfully!!! Thank you so much!"

**Comment by jatinganhotra** [comment]
@ssoulless You're welcome. When I was learning these things, I also got confused a lot. Glad the experience was less painful for you.

**Comment by thiagovsk** [comment]
@jatinganhotra 

how you solved the problem?

I'm trying to get and only

OAuthException, code: 15 message: (# 15) This method must be called with an app access_token. [HTTP 400]

i tryed with https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=me%3Ffields%3Did%2Cname&version=v2.3

```ruby
b = Koala::Facebook::API.new(access_token,app_secret)
b.put_connections('me', "notifications", template: "foo", href: "bar")
```
why he complains if I already have the access token?

**Comment by jatinganhotra** [comment]
@thiagovsk Did you try my last comment on Mar 12, 2013? I haven't used Koala after that, so I'm not up-to-date with the API.

**Comment by thiagovsk** [comment]
@jatinganhotra No problem, i just use another gem with support the new version of API.

**Comment by Pipinha** [comment]
@thiagovsk , I've got this message "Koala::Facebook::ClientError: type: OAuthException, code: 200, message: (#200) Only web canvas apps can send app notifications [HTTP 403]"

I think is something in my app's configuration. Do you guys know where?

**Comment by arsduo** [comment]
That last one sounds like Facebook may have (possibly changed the) restrictions on what kind of apps can send notifications. 

Are any of you still having issues with this? It doesn't sound specifically like a Koala issue, but if there's something that I can change with the gem or the documentation to make it easier, let me know.

**Comment by arsduo** [comment]
I'm going to close the issue since it's  been a while; please reopen it if you are still having a problem with the gem or open a new one if needed. Thanks for using Koala!
