### ISSUE TITLE
iframe Invalid signatures when user is logged out of facebook?

### ISSUE THREAD

**Issue by gingerlime** [arsduo/koala#305]
I just came across a strange issue. Occasionally we were seeing `Invalid signature` error from `parse_signed_request`. Inspecting the actual content, everything looked fine, apart from the signature that did not match... The request itself didn't seem malicious or contained any particularly strange info.

We tried to work out how to reproduce it, and then we've seen that if you access the iframe app on facebook without being logged-in (to facebook), then it happened. We're not sure it's the only way to reproduce it, or maybe it happens under different circumstances.

I'm wondering if anybody else has experienced something similar?

**Comment by arsduo** [comment]
I'm guessing this is no longer an active issue (sorry about the crazy late response), so I'm going to close it, but please feel free to reopen it if it's still a problem. That sounds like a strange bug -- hopefully Facebook fixed it.
