### ISSUE TITLE
Exception handling in batch actions

### ISSUE THREAD

**Issue by toptierlabs** [arsduo/koala#308]
I have the following code:

arr = graph.batch do |batch_api|
   chains.each do |chain|
       batch_api.get_picture(chain.facebook_id, {:type => 'large'})
   end 
end

It invokes the following code in graph_api.rb file of the gem:

def get_picture(object, args = {}, options = {}, &block)
  # Gets a picture object, returning the URL (which Facebook sends as a header)
  resolved_result = graph_call("#{object}/picture", args, "get", options.merge(:http_component => :headers)) do |result|
      result["Location"]
  end
  block ? block.call(resolved_result) : resolved_result
end

However, one of the hundreds of calls that I do fails, due to the following FB error:
"Page ID 235385989915990 was migrated to page ID 265147080261006.  Please update your API calls to the new ID".
When that happens I get the error: undefined method `[]' for #Koala::Facebook::ClientError:0x007ff2dbeaef68
and the entire batch block fails! 
When that happens I expect the error to be handled internally and added to the resulting array. 

Does it make sense?

**Comment by pratik60** [comment]
@arsduo Did you figure out a way for the same?

In my code, the error goes entirely to data

data is #<Koala::Facebook::ClientError: type: OAuthException, code: 100, message: (#100) link is not properly formatted [HTTP 400]>

while e is #<NoMethodError: undefined method `[]' for #<Koala::Facebook::ClientError:0x007fcb71f841b8>>

How do I capture the error right in a batch call?
```
batch_api.put_object(ad_account, 'adcreatives', crtv.options) do |data|
            puts data
            crtv.query_result = data
            begin
              crtv.id = data['id']
              crtv.created_in_fb = true
              success += 1
            rescue Exception => e
              fail += 1
              crtv_failed << crtv
              byebug
              Rails.logger.debug('Creative #{crtv.query_result}')
              crtv.error = 'Error creating creative' + e.fb_error_user_msg
            end
          end
```

**Comment by pratik60** [comment]
Sorry strike that, I figured it out

```
         batch_api.put_object(ad_account, 'adcreatives', crtv.options) do |data|
            crtv.query_result = data
            begin
              crtv.id = data['id']
          rescue
              crtv.error = 'Error creating creative' + handle_facebook_error(data)
           end
```

```
def handle_facebook_error(e)
  if e.fb_error_user_msg.present?
    return e.fb_error_user_msg
  elsif e.fb_error_message.present?
    return e.fb_error_message
  else
    return e
  end
end
```

**Comment by arsduo** [comment]
Glad you figured it out! Sorry about the late response -- I appreciate you following up. Let me know if you run into any other issues.
