### ISSUE TITLE
Using Koala inside rails_admin for after creation posting to Facebook page through an App

### ISSUE THREAD

**Issue by minakolta** [arsduo/koala#313]
``` ruby
 @oauth = Koala::Facebook::OAuth.new(Kenana::Application.config.facebook_app_id, Kenana::Application.config.facebook_app_secret, "http://localhost:8080/product/new/")
  code = @oauth.url_for_oauth_code(:permissions => "read_stream,publish_stream,offline_access,manage_pages")
  puts @oauth.get_access_token_info(code).inspact
```

What i'am trying to do is to get the authentication token (a permanent one) trough my facebook app_id and app_secret 
but i have this exception 

``` ruby
Koala::Facebook::OAuthTokenRequestError in RailsAdmin::MainController#new

type: OAuthException, code: 100, message: Invalid verification code format. [HTTP 400]
```

any body can explain ?

**Comment by arsduo** [comment]
Apologies for never getting to this. This is obviously too late to be useful, but in general the Facebook documentation should point anyone else with the same question in the right direction, and [facebook.stackoverflow.com](http://facebook.stackoverflow.com) is a great resource in general.
