### ISSUE TITLE
Strange comment id format

### ISSUE THREAD

**Issue by targence** [arsduo/koala#315]
I have several old posts, there are two as example:

```
162805193749522_196070250430270
162805193749522_212568245424768
```

When I request 'comments' connections

```
post_id = '162805193749522_196070250430270'
fb.get_connections(post_id, 'comments', {fields: 'id,from,created_time,like_count', filter: :stream, date_format: :U}) }
```

I get comments ids in very strange format

```
'162805193749522:196070250430270:63_2715946'
```

I'm trying to get comments likes.

This request return error

```
fb.get_connections('162805193749522:196070250430270:63_2715946', 'likes', { date_format: :U}) }
```

```
type: OAuthException, code: 1, message: An unknown error has occurred. [HTTP 500] 
```

Ok, let's modify id a little =)

```
'162805193749522:196070250430270:63_2715946' —> '162805193749522_196070250430270_2715946'
```

It's OK

```
fb.get_connections('162805193749522_196070250430270_2715946', 'likes', { date_format: :U}) } 
```

```
=> []
```

Graph API Explorer understands this strange comment id format

![screen shot 2013-07-17 at 16 33 42](https://f.cloud.github.com/assets/415928/811660/4d1467a4-eedd-11e2-8510-37b59484707e.png)

But don't return likes ( "like_count": 1) =(

![screen shot 2013-07-17 at 16 34 15](https://f.cloud.github.com/assets/415928/811668/66a70208-eedd-11e2-915b-56fc9b8c5fcc.png)

![screen shot 2013-07-17 at 16 34 30](https://f.cloud.github.com/assets/415928/811669/718ee12c-eedd-11e2-98bb-9bc9f8a08d78.png)

Not returning comments likes – it's FB bug. I understand. We can't do anything.
But at least Koala should understand such strange comment id format and don't return error.

**Comment by arsduo** [comment]
Closing since it's been two years. Please reopen if this is still an issue.
