### ISSUE TITLE
Koala::Facebook::APIError when doing next_page

### ISSUE THREAD

**Issue by nbantatua** [arsduo/koala#320]
I kept receiving

<pre>
<code>
@events = @graph.get_connection("me","events")
@events.next_page
Koala::Facebook::ServerError: {"error_code":1,"error_msg":"An unknown error occurred"} [HTTP 500]
or
@graph.get_page(@events.next_page_params)
Koala::Facebook::ServerError: {"error_code":1,"error_msg":"An unknown error occurred"} [HTTP 500]
</code>
</pre>

so far this only happens for event collections; doing next_page on others such as posts is fine. Running through page results of events from graph explorer works ok as well.

Anybody else having the same issue? Thanks!

**Comment by nitvik** [comment]
probably you guys requested too much data.

Try reducing the limit.
