### ISSUE TITLE
Ruby 2.0 issue effecting all versions of Koala

### ISSUE THREAD

**Issue by KensoDev** [arsduo/koala#346]
Recently, I have upgraded a big application to Ruby 2.0 (all gems remained the same).

I am running version 1.4.0 of Koala (Upgraded all the way up to the RC and the problem persists).

What happens is when you run any Koala API command such as:

``` ruby
graph = Koala::Facebok::API.new(token)
graph.get_object 'me'
```

Exception is thrown

```
MultiJson::DecodeError: 399: unexpected token at ''
```

Digging through the source, the problem originates in the API class, here:

``` ruby
body = MultiJson.decode("[#{result.body.to_s}]")[0]
```

What happens is that `result.body` is actually a Gzipped version of the JSON response.

This is because a basic change in the Ruby 2.0 `Net::HTTP` class, that if you don't add a header, it will default to a header that accepts Gzip, so Facebook API will return a Gzipped response which breaks everything down the chain.

You can see the source of the Ruby code stdlib here:

https://github.com/ruby/ruby/blob/v2_0_0_353/lib/net/http/generic_request.rb#L39

The problem exists all the way down to `p247` (did not check lower versions)

At a first glance, this seems like a JSON issue, or a multi_json issue, but actually nothing helps, replacing the `engine` or `adapter` in newer version doesn't help as well, you cannot fix this issue without patching HTTP.

The only possible with for it would be inside Koala to make sure that you don't pass the header.

For the meantime, if you run Ruby 2.0 and use Koala, you can patch the HTTP response to decode the JSON yourself

``` ruby
module DecodeHttpResponseOverride
  def initialize(h,c,m)
    super(h,c,m)
    @decode_content = true
  end

  def body
    res = super
    if self['content-length']
      self['content-length']= res.bytesize
    end
    res
  end
end

module Net
  class HTTPResponse
    prepend DecodeHttpResponseOverride
  end
end
```

Keep in mind this code is Ruby 1.9 incompatible, so if you want to run it in a mixed ruby env, just check for Ruby version before you `prepend`

``` ruby
if RUBY_VERSION > "1.9.3"
  prepend DecodeHttpResponseOverride
end
```

Again, this is NOT only a Koala bug, this breaks Twitter, Flickr and other JSON API's that respect the accept header and send back Gzip.

I will be more then happy to post a PR that fixes this, but I see that there are already a few 2.0 branches that deal with different things, so I thought I'd get this out there first.

**Comment by mekhovov** [comment]
this issue fixed in v 1.5.0 `gem 'right_http_connection', '1.5.0'`
this is PR https://github.com/rightscale/right_http_connection/pull/20
