### ISSUE TITLE
(No route matches [POST] “/”) error inside apps.facebook..

### ISSUE THREAD

**Issue by toufiqueimam** [arsduo/koala#351]
Getting error (No route matches [POST] “/”) while trying to access the app inside facebook. Stackoverflow link for details
http://stackoverflow.com/questions/20734329/ruby-on-rails-facebook-canvas-app-no-route-matches-post

**Comment by arsduo** [comment]
I'm guessing this is no longer an active issue (sorry about the crazy late response), so I'm going to close it, but please feel free to reopen it if it's still a problem. Looks like you got answers on StackOverflow.
