### ISSUE TITLE
graph.put_wall_post: posting a unique link from a controller or a worker keeps returning [HTTP 500]

### ISSUE THREAD

**Issue by lucasgerard** [arsduo/koala#356]
Hi everybody,

I wanna post a link on a group's wall following the process below:

An user creates an event:

``` ruby
def create
        @event_token = SecureRandom.hex(4)
        @event = Event.new(title: params[:title],
                             url: ENV["URL"] + "/events/#{@event_token}")

        if @event.save
          InvitationsWorker.perform_async(@event.id, params[:oauth_token], params[:invited_users_tokens], params[:invited_groups_tokens], params[:message])
          render json: { event: @event, status: "success" }
        else
          render json: { status: "error" } 
        end
end
```

And as the event is saved, an invitation is posted on the selected group's wall by the InvitationsWorker:

``` ruby
def perform(event_id, oauth_token, invited_users_tokens, invited_groups_tokens, message)

    @event = Event.find(event_id)
    @graph = Koala::Facebook::API.new("#{oauth_token}")

    @group_id = invited_groups_tokens.to_i

    @graph.put_wall_post("test", { :name => "test", :link => "#{@event.url}" }, "#{@group_id}")
end
```

The event is perfectly saved but the worker fails, returning: 
Koala::Facebook::ServerError: type: OAuthException, code: 2, message: An unexpected error has occurred. Please retry your request later. [HTTP 500]

I tried running the same command in the terminal with a saved event, the code below works fine:

```
$ @graph = Koala::Facebook::API.new( "#{User.first.oauth_token}" )
$ @event = Event.first
$ @group_id = 528596717222285

$ @graph.put_wall_post("test ?", {:name => "test", :link => @event.url}, "#{@group_id}")
```

So the problem seems to come from the definition of `:link => #{@event.url}` and the fact that this definition takes place in a controller or a worker.

I really looked into this problem for a long time and I hope that somebody will have a clue about the problem it comes from!

Thank you in advance,

Lucas

**Comment by arsduo** [comment]
I'm guessing this is no longer an active issue (sorry about the crazy late response), so I'm going to close it, but please feel free to reopen it if it's still a problem. 500 errors mean something went wrong on Facebook's side and usually that goes away once they fix the bug.
