### ISSUE TITLE
Canvas App is not displayed by default

### ISSUE THREAD

**Issue by ghost** [arsduo/koala#358]
Not really an issue related to koala but propably something for the wiki since developers might use koala and protect others from wasting time for researches :)

Problem:
f you make a canvas-app which will be display inside the facebook-iframe, by default rails 4 is sending some headers to permit the display of iframe content on foreign websites, due security reasons.

```
config.action_dispatch.default_headers['X-Frame-Options'] = "ALLOW-FROM https://apps.facebook.com"
```

this line inside your application.rb will fix it. You need to allow apps.faceboom.com to display it.

**Comment by arsduo** [comment]
Apologies for the really late response. Google should be useful for finding this, but if you'd like to add that to the wiki page, that'd be awesome.

(Resolving since it's been a while.)
