### ISSUE TITLE
Search does not return all public posts

### ISSUE THREAD

**Issue by ejsantos** [arsduo/koala#359]
Hello,

I'm writing an app that gets public posts by using 

```
oauth = Koala::Facebook::OAuth.new(Facebook::APP_ID.to_s, Facebook::SECRET.to_s)
fb_graph = Koala::Facebook::API.new(oauth.get_app_access_token)
posts = fb_graph.search('#100happydays', {type:post})
posts.each {|p| puts p['id']}
```

It currently returns only 2 posts. 

But when searching using the Graph API Explorer tool from Facebook, I get a lot more

```
/search?q=%23100happydays&type=post
```

**Comment by arsduo** [comment]
Hi! Apologies for never responding. If you figured it out (or if you're still encountering it) I'd be interested to hear, but I'm guessing this is no longer an active issue.

**Comment by arsduo** [comment]
I'm going to close the issue since it's  been a while; please reopen it if you are still having a problem with the gem or open a new one if needed. Thanks for using Koala!
