### ISSUE TITLE
Koala get next 25 comments using graph api

### ISSUE THREAD

**Issue by robertliuling** [arsduo/koala#360]
Hi,

I have the following code that's getting the comments from a facebook post, however this is only getting me latest 25 comments, how can i get the next 25 using Koala api?

Thanks,

@oauth = Koala::Facebook::OAuth.new(fb_app_id, fb_app_secret)
@app_access_token = @oauth.get_app_access_token
@graph = Koala::Facebook::API.new(@app_access_token)

@all_comments = @graph.get_object(fb_post_id, "fields" => "comments.summary(true)")["comments"]

**Comment by arsduo** [comment]
Thanks, @Aeze! I'm going to close this now given how old it is, but if you have any issues related to the gem, please open another ticket and I'll take a look!
