### ISSUE TITLE
Get connections returns empty friends list?

### ISSUE THREAD

**Issue by dustineichler** [arsduo/koala#384]
I think this is standard behavior now. Correct me if I'm wrong. Facebook has changed their API. You can no longer grab your "friends" list unless your "friend" is using the application you're using. Can someone clarify and confirm?

``` ruby
profile = @graph.get_object("me")
friends = @graph.get_connections("me", "friends")
# friends is empty!
```

**Comment by prororgeek** [comment]
Koala gem in good for fetch the facebook profiles data.

**Comment by loureirorg** [comment]
Right now, this won't works anymore. Facebook disabled the "friends list" feature on April 30 2015 ([link](http://www.techtimes.com/articles/49459/20150429/facebook-prepares-to-shut-down-friends-data-api-why-this-is-good-for-privacy.htm)). Right now, by calling this endpoint, it will return only the friends who are using your app, which normally is an empty array. 

But there's a workaround. You need to create a new Facebook App as a "Facebook Canvas" and check it as a "Game". Then, you can use an "invitable_friends" call to get the user's friends.
```ruby
friends = @graph.get_connections("me", "invitable_friends")
```

**Comment by webbr88** [comment]
Thanks for the update @loureirorg !

I'll give this solution a try

**Comment by IronLeash** [comment]
invitable_friends will not work after february 2018 since facebook made app invites also deprecated.
