### ISSUE TITLE
Settings for Retry when there is a facebook api 500 error.

### ISSUE THREAD

**Issue by sahin** [arsduo/koala#389]
@arsduo we use your gem heavily, %2-%5 we are getting fb api errors caused FB api, 

Like
- Network is unreachable - connect(2) for "graph.facebook.com" port 443
- type: OAuthException, code: 2, message: An unexpected error has occurred. Please retry your request later. [HTTP 500]
- type: OAuthException, code: 1

It will be super great if we can put a retry setting if there is fb api error. 

We can do PR, is it ok for you? What do u think?

**Comment by pratik60** [comment]
@arsduo We have a batch call to the facebook api to create ad creatives, but it intermittently fails. So, when we split requests and send it in 50's, out of 400, we have 0-15 failing. On one or two retries all go through....Any advisable way to create a retry, or do I just catch the failing ones, and put it back in the batch call.....If you have sample code, doing something like this, I would love it if you could share partial code....
