### ISSUE TITLE
How to determine when token is expired because user changed password

### ISSUE THREAD

**Issue by istan** [arsduo/koala#392]
Running into this problem in a production app... I get back an OAuth error from Facebook for an expired token if I try to make a POST on behalf of a user that has changed her password, for example: 

```
graph.put_wall_post("hello world",{},uid) ==> error :(
```

I can handle that error, but it's too late - the user's intended action has already failed. I want to check the status of my user's token before my user tries to do anything with it. So, given that I have a koala object:

```
graph = Koala::Facebook::GraphAPI.new(token)
```

How can I "test" the validity of the token without trying to make a POST on the user's behalf? So that I can tell the user she needs to renew her auth BEFORE a POST that she triggers fails and now she's frustrated. e.g. If I wanted to run a job every night that checked the validity of the tokens for all of my users, what would be the way to do that using Koala? I can't attempt a .put_wall_post() for all of my users because if the token is valid I've just spammed their walls. 

I've tried the other API methods in Koala (like .get_connections("me", "friends"), .search(), etc) and they all return valid responses even with the now-invalid-because-of-pw-change token. Any suggestions?

Many thanks!

**Comment by arsduo** [comment]
Apologies for the late response! I'm sure you've figured something out by now, but tl;dr: I'm not sure. As far as I've always seen, all requests fall once the token expires.

[facebook.stackoverflow.com](http://facebook.stackoverflow.com) is a good place to ask questions about the Facebook API itself (I only know sections of it). 

Closing this issue, feel free to reopen is there's anything that would be good to change in Koala around this.
