### ISSUE TITLE
It would be nice if mock http server was available to koala's users

### ISSUE THREAD

**Issue by fagiani** [arsduo/koala#40]
Hey Alex,

I loved this gem and I am using it!

I thought it would be good if instead of the mock class belong in the spec tree it would be organized within the koala's code so actual users of the gem could use it as an advantage to offline testing.

If this is something you think it is doable and a real benefit, I can help to refactor with some guidance from you.

Thanks.

**Comment by arsduo** [comment]
Ah, the very olden days! This has long since not been a live issue -- nowadays there are so many better ways to handle doing development, among them VCR (which I hope to port the test suite to someday).

Hope you've all had a great 5.5 years! Closing this issue.
