### ISSUE TITLE
GraphCollection next_page method throws OAuthException code 2500

### ISSUE THREAD

**Issue by paranoidsp** [arsduo/koala#406]
Hi
  I've been facing this problem since today afternoon. Using the next_page method on the GraphCollection object throws the following error

```
Koala::Facebook::AuthenticationError: type: OAuthException, code: 2500, message: Unknown path components: /act_xxxxxxxxxxx/adcampaigns [HTTP 400]
from  xxxx/ruby-2.1.0/gems/koala-1.10.1/lib/koala/api/graph_api.rb:503:in `block in graph_call'
```

The get_connection query goes of without a hitch, but only the next_page query raises the above error. I've tried it on several different objects, and accounts, and it has resulted in the above error repeatedly.

Anyone know a fix for this? 

Thanks,
Karthikeya

**Comment by arsduo** [comment]
Hi all — I released a new test version of Koala last week, and want to see if you could test it out and if so, if it solved the problem. If so, I'll release it this week.

**Comment by egukin** [comment]
Still having this problem in koala-1.10.1
