### ISSUE TITLE
Active token is required...

### ISSUE THREAD

**Issue by weightyfoe** [arsduo/koala#411]
I'm following your examples like so.

Created a new app on my (personal) fb account - got the app_id and app_secret codes

Console:
o = Koala::Facebook::OAuth.new(app_id, app_secret)
=> #<Koala::Facebook:: etc etc>
token = o.get_app_access_token
=> "6058473... a long string"
g = Koala::Facebook::API.new(token)
=> #<Koala::etc @access_token=<token from above>, @app_secret=nil>
g.get_object("me")
=> OAuthException, code 2500, An active access token must be used
g.get_object("koppel")
=> Same error

I ran the same but this time passing in my app_secret to the Facebook::API.new call as well as the token - same deal.
I'm clearly doing something wrong, but what?

Sorry if this is not the right place for this message.

**Comment by arsduo** [comment]
I've updated the docs to reflect that most calls need an access token now. Thanks for pointing this out!
