### ISSUE TITLE
How to get access token through ruby code?

### ISSUE THREAD

**Issue by vijikumar55** [arsduo/koala#421]
Hi,

I am using Hull.io to logging in users into my application. I am using koala to post video links to facebook. How to get access token using ruby code?

**Comment by arsduo** [comment]
Apologies for the late response, the issue backlog grew and I missed some. It sounds like the Facebook docs are the right place for you to look (though I'm sure you've figured it out by now) and [facebook.stackoverflow.com](http://facebook.stackoverflow.com) is a great resource in general.
