### ISSUE TITLE
`get_picture` doesn't return json data

### ISSUE THREAD

**Issue by morgoth** [arsduo/koala#424]
I want to use `/user-id/picture` endpoint with `redirect: false` option, to get info about `is_silhouette` attribute. https://developers.facebook.com/docs/graph-api/reference/v2.2/user/picture?locale=pl_PL

This is not possible with Koala right now, which assumes reading redirect url from response headers https://github.com/arsduo/koala/blob/65a0b31278ac10e2970cba39b58757ddee31f9fe/lib/koala/api/graph_api.rb#L180

Would you accept a patch, that would return json data when `redirect: false` is passed?
Or maybe you have some better idea how to solve this issue.

For now I workaround the issue by: `graph_call("/#{user_id}/picture", {redirect: false}, "get")`

**Comment by arsduo** [comment]
Thanks for submitting the PR! I'll close this issue in favor of #432.
