### ISSUE TITLE
Access Token suddenly required for public page access after upgrading from 1.9 to 1.10

### ISSUE THREAD

**Issue by jensb** [arsduo/koala#426]
With koala 1.9.0 (specifically, 5a5b847f36), I was able to do e.g.

```
data = Koala::Facebook::API.new.get_object("teslamotors")
```

to get information on Facebook for a public page or profile (in this case, the Tesla car company). With koala 1.10.0 (65a0b312), the exact same call results in

```
Koala::Facebook::ClientError (type: OAuthException, code: 104, message: An access token is required to request this resource. [HTTP 400]):
```

Is this intentional? Why?

**Comment by kevinjbayer** [comment]
Having this same issue on 2.0.0.

Is it just mandatory now to have an access token to get info from a public page?

**Comment by arsduo** [comment]
You can specify which version of the API you want to use, so for apps that can access versions before 2.2 you can manually set it to use 2.1 or earlier. That said, Facebook is going to at some point require an access token for all new apps (as they release new version they eventually ratchet up the minimum version that new apps can access), so it's something to prepare for.

**Comment by kevinjbayer** [comment]
Thanks for the reply and the info, @arsduo. I didn't realize that I could just use the app access token to get the info that I needed. I was mainly wanting to avoid needing the user to authenticate and I think I've accomplished that.

**Comment by bistanil98** [comment]
have same problem and using 2.1 version,as per this discussion we need access token compulsory

**Comment by arsduo** [comment]
@bistanil98 I thought about making the access token compulsory, but according to Facebook docs there are still a few endpoints that don't require one("Most API calls must be signed with an access token" on https://developers.facebook.com/docs/graph-api/using-graph-api, viewed today). Given that I don't want to make the change until it's absolutely necessary. 

I will however update the read me to indicate that use without an access token is generally not very useful.

**Comment by arsduo** [comment]
I've updated the docs to reflect that most calls now require an access token. Thanks for pointing that out!
