### ISSUE TITLE
Bug in version 1.10.1

### ISSUE THREAD

**Issue by tenaz3** [arsduo/koala#428]
Hi, I was using koala version '1.9.0' when I switch to '1.10.1' my code stopped to work. 
Piece where my code has broken:
```
list = graph.get_object("#{eid}/attending")
list = list.next_page # here when call next page
```
```
Exception Koala::Facebook::AuthenticationError (type: OAuthException, code: 2500, message: Unknown path components: /:eid/attending [HTTP 400])
```

**Comment by velles** [comment]
+1 , I have the same issue. It looks like after versioning was introduced, the paging does not work correctly.

**Comment by velles** [comment]
@tenaz3 it looks like it's fixed in the newest version. I just tested it -  v1.11.0rc ..

this might be the commit that fixes it but I might be wrong about that - https://github.com/arsduo/koala/commit/5b3ad7ad8877cb76e66173723e8c7bd87a69d546

**Comment by arsduo** [comment]
I’ll be releasing the full version this week.

**Comment by velles** [comment]
awsome , thanks @arsduo
