### ISSUE TITLE
Can't get my app Approved by facebook

### ISSUE THREAD

**Issue by maxgronlund** [arsduo/koala#434]
I have testet with at least 10 test users and 4 testers, I'm not able to make it fail, but I keep getting the same message from facebook

'Your Open Graph action failed to publish on any of the Platforms you submitted. Make sure the action is working properly by publishing the action with a test user before resubmitting.'

I posted some more details on 
http://stackoverflow.com/questions/27967576/unable-to-get-facebook-open-graph-action-approved-using-rails-and-the-koala-gem

If anyone would like to try posting please go ahead and let me know
So I can to make you a tester for my app on facebook

**Comment by arsduo** [comment]
Apologies for the late response, the issue backlog grew and I missed some. I don't know the answer to this (and assume you figured something out); I saw you've already posted on StackOverflow, which is the better place to get answers on what's happening with the Facebook API itself (as opposed to the Koala gem).
