### ISSUE TITLE
Method debug_token ignores appsecret_proof

### ISSUE THREAD

**Issue by istana** [arsduo/koala#438]
I'm not really sure if this is bug or feature, but when I initialize API with appsecret_proof, *debug_token* won't pass, but direct call is ok.

````
@graph = Koala::Facebook::API.new(tok, 'myappsecret')
1.9.3-p551 :004 > @graph.debug_token(tok)
Koala::Facebook::ClientError: type: GraphMethodException, code: 100, message: Invalid appsecret_proof provided in the API argument [HTTP 400]

1.9.3-p551 :007 > @graph.api('debug_token', :input_token => tok)
 => {"data"=>{"app_id"=>".....
````

**Comment by nhattan** [comment]
What version of Koala you are using?

**Comment by prettyfuntherapy** [comment]
Hi,

I have the same Issue. Using Koala 1.10.1

Any idea ?

**Comment by nhattan** [comment]
According to the [changelog](https://github.com/arsduo/koala/blob/master/changelog.md), you have to update to version newer than [1.9.0](https://github.com/arsduo/koala/blob/master/changelog.md#v190). It supports appsecret_proof parameters.

**Comment by nhattan** [comment]
OR you should check your appsecret_proof setting in your fb app then choose the right app in [Graph API Explorer](https://developers.facebook.com/tools/explorer)

**Comment by istana** [comment]
I have used 1.9.0 I think, when I reported this. I will try with a newer version

**Comment by arsduo** [comment]
Did you figure it out? It looks from the code like the appsecret_proof should be properly passed in with the debug_token method (it all routes through graph_call => api => HTTPService).

If you can still reproduce this, can you turn on Koala's debug mode and share the output you get, and I'll reproduce?

**Comment by istana** [comment]
I'll look into it in a few days if there's still an issue

**Comment by istana** [comment]
with Koala 2.4.0 it works properly now:
```
2.3.1 :014 > @graph.api('debug_token', :input_token => tok)
 => {"data"=>{"app_id"=>"18", "application"=>"seedling", "expires_at"=>1476273600, "is_valid"=>true, "scopes"=>["user_friends", "email", "public_profile"], "user_id"=>"51"}}
2.3.1 :015 > @graph.debug_token(tok)
 => {"data"=>{"app_id"=>"18", "application"=>"seedling", "expires_at"=>1476273600, "is_valid"=>true, "scopes"=>["user_friends", "email", "public_profile"], "user_id"=>"51"}}
```

**Comment by brianlaw033** [comment]
I am getting this, any fix?

**Comment by istana** [comment]
Hi, do you use the latest version of koala?
