### ISSUE TITLE
Not able to add/publish subscrption on facebook for real time updates

### ISSUE THREAD

**Issue by sshinde-systango** [arsduo/koala#439]
Hi,

I'm trying to add/publish a subscription for real time updates via Graph API Explorer. Here is my requested POST url

https://graph.facebook.com/v2.2/{app_id}/subscriptions/?object=user&fields=friends&verify_token=thisisaverifystring&access_token=my_app_token&callback_url=http://mydomain/auth/facebook/callback/

But I'm getting error response:

{ "error": { "message": "(#2200) callback verification failed: ", "type": "OAuthException", "code": 2200 } }

Also I have defined same callback URL twice in my routes to handle GET as well as POST requests. 

I've tried with the Koala gem method to add subscription:

@updates = Koala::Facebook::RealtimeUpdates.new(:app_id => app_id, :secret => secret)
@updates.subscribe("user", "first_name, last_name", callback_url, verify_token)

But getting the same response:

Koala::Facebook::ClientError: type: OAuthException, code: 2200, message: (#2200) callback verification failed:  [HTTP 400]

My API request mentioned above from Graph API as well as Koala gem method is hitting my callback url but I'm also getting error in server logs

Started GET "/auth/facebook/callback/?hub.mode=subscribe&hub.challenge=246450618&hub.verify_token=thisisaverifystring" for 66.220.158.118 at 2015-02-12 19:24:12 +0530 I, [2015-02-12T19:24:12.530395 #18960] INFO -- omniauth: (facebook) Callback phase initiated. E, [2015-02-12T19:24:12.530916 #18960] ERROR -- omniauth: (facebook) Authentication failure! no_authorization_code: OmniAuth::Strategies::Facebook::NoAuthorizationCodeError, must pass either a code (via URL or by an fbsr_XXX signed request cookie)

OmniAuth::Strategies::Facebook::NoAuthorizationCodeError (must pass either a code (via URL or by an fbsr_XXX signed request cookie)): omniauth-facebook (2.0.0) lib/omniauth/strategies/facebook.rb:151:in with_authorization_code!' omniauth-facebook (2.0.0) lib/omniauth/strategies/facebook.rb:71:incallback_phase' omniauth (1.2.2) lib/omniauth/strategy.rb:227:in callback_call' omniauth (1.2.2) lib/omniauth/strategy.rb:184:incall!' omniauth (1.2.2) lib/omniauth/strategy.rb:164:in call' omniauth (1.2.2) lib/omniauth/strategy.rb:186:incall!' omniauth (1.2.2) lib/omniauth/strategy.rb:164:in call' omniauth (1.2.2) lib/omniauth/builder.rb:59:incall' rack (1.5.2) lib/rack/etag.rb:23:in call' rack (1.5.2) lib/rack/conditionalget.rb:25:incall' rack (1.5.2) lib/rack/head.rb:11:in call'

I'm assuming here is something wrong with the verify token but I'm not sure how can I get this token.

Please comment

**Comment by LuckyThirteen** [comment]
I managed to create a subscrption with [this](https://github.com/LuckyThirteen/RataToUille/blob/master/ratatouille.rb), maybe it helps.

**Comment by arsduo** [comment]
Sorry about the late response! 

It's been awhile since I've used the realtime updates API, but I believe that that error message means that when Facebook went to call back to your server, it didn't get the response it was expecting. Have you verified what happened when the callback came?

Since others have been able to make subscriptions, it's probably not an issue with the gem. Since it's also been a while (sorry again!) I'm going to close the issue, but please reopen it if it turned out to be a problem with the Ruby code.
