### ISSUE TITLE
Deprecated Mutual Friends

### ISSUE THREAD

**Issue by daniellecs** [arsduo/koala#441]
When using Koala's @graph.get_connections("me", "mutualfriends/#{friend_id}") method, the following error results: type: OAuthException, code: 12, message: (#12) user/mutual_friends is deprecated for versions v2.0 and higher [HTTP 400].

**Comment by arsduo** [comment]
Facebook no longer allows you to access mutual friends that way -- I believe there's another way. I don't know if offhand, if you look in their developer docs, they'll definitely have some info.

**Comment by antonshevchenko** [comment]
Had the same problem. This is what I did:

```
@graph.get_object("someuser", {fields: ["context"}) { |data| data["context"]["mutual_friends"]["data"] }
```

This will return an array of mutual friends.

Hope this helps!

**Comment by kennygeiler** [comment]
@antonshevchenko what exactly are you supposed to put into those fields you just wrote, 
someuser is "me" and then where do you specify the other user

**Comment by antonshevchenko** [comment]
The `"someuser"` is the other user. When you do `get_object` it already knows you `"me"` is.

**Comment by kennygeiler** [comment]
@antonshevchenko and the rest like after "someuser", i can leave the same or do I need to change that to something?

**Comment by antonshevchenko** [comment]
The rest should be good as is. It basically extracts the exact part of the data that contains mutual friends.

**Comment by kennygeiler** [comment]
@antonshevchenko its not throwing an error but the code doesn't return anything, and I went to my facebook dev for my app and set the test users as friends with each other

**Comment by antonshevchenko** [comment]
Did you try doing the correct API call on Facebook's Graph API explorer to see that it actually returns mutual friends?

**Comment by kennygeiler** [comment]
@antonshevchenko there is no error and no return value the code just executes in the shell and does nothing so that makes me confused as to if there are no mutual friends ( which is wrong because the test users I am working with are mutual friends) or if the call was not working correctly

**Comment by antonshevchenko** [comment]
Not sure how to help out without seeing what you are actually running in your shell. Are you sure you are properly logged in with Facebook and your `@graph` object works for other API calls?

**Comment by kennygeiler** [comment]
@antonshevchenko what are you passing as some user? their uid, name, etc? I have tried it with their id, and name and both of them throw no errors but do not return with anything and yeah other calls have worked

**Comment by antonshevchenko** [comment]
We are passing the friend user's `uid` as a string.

**Comment by antonshevchenko** [comment]
If you want, you could try removing the block after the call, so you will get all of the raw data returned from the API.

So something like this:

```
graph.get_object("someuser", {fields: ['context']})
```

**Comment by kennygeiler** [comment]
@antonshevchenko when I do that, I get no errors but no response either

**Comment by JikkuJose** [comment]
Anyone has a solution for this? Am stuck at this, seems FB is trying to block mutual friend API.

**Comment by antoinegergy** [comment]
Solution for me: 
```ruby
graph.get_object('user_id', {fields: ["context.fields(all_mutual_friends)"]})
```
Please note that i use [Koala with Rails](https://github.com/arsduo/koala/wiki/Koala-on-Rails),  so my `app_id` and `secret_key` are set. This is important because koala use them to generate the `appsecret_proof` that is required for this request.

**Comment by tappella** [comment]
hey @7fELF , thanks for the info.

I don't know, but it seems there are some issues with Facebook, it brings mutual friends for some users but for others it doesn't.

Anyone facing the same issue?
