### ISSUE TITLE
Event cover

### ISSUE THREAD

**Issue by folivi** [arsduo/koala#442]
hi all,
How can I get an event cover picture?
thanks for your help

**Comment by Tetse** [comment]
Hey,

I've got a similar problem. Did you find a solution yet?

**Comment by folivi** [comment]
yep. in fact you get a cover hash in the response from the graph.get_obect(event_id) call.
It contains a source offset_x and offset_y attribute representing the event image

**Comment by arsduo** [comment]
Cool! Glad you found the answer; sorry I wasn't able to respond in time. Have a great week!
