### ISSUE TITLE
sanitize_request_parameters incorrectly joining Array params

### ISSUE THREAD

**Issue by mdimas** [arsduo/koala#443]
I have an opengraph event that takes an Array as one of the arguments (say `users[]`). sanitize_request_parameters is joining this argument into a comma-separated string, and then Facebook is trying to use that argument as a single string rather than as an array of strings. I confirmed that if I don't join the strings and leave them as an Array then Facebook is happy. I think that in general sanitize_request_parameters should not squash values if the key contains brackets `[]`.

**Comment by arsduo** [comment]
Hi! Sorry about the extremely late response -- this should be fixed at last with #457. Let me know if you're still having issues with this with the new version. (Sorry about the extremely late response!)
