### ISSUE TITLE
If I use Koala version 1.11.1, does that mean I am automatically using Facebook's v2.2 API?

### ISSUE THREAD

**Issue by serv** [arsduo/koala#444]
I recently updated Koala gem from 1.7.0rc1 to 1.11.1.
Made a few changes to ensure that everything is working. 
Is there anywhere in Koala gem I have to set manually to use Facebook's v2.2 API?
Or by using Koala version 1.11.1, I am automatically using Facebook's v2.2 API?

**Comment by arsduo** [comment]
Hi Jason,




The version of the Facebook API you’re using depends on the Facebook app, not Koala. If it’s a new Facebook app, whatever the current version of the API is will be what the app has. If you aren’t on 2.2 but want to be, you’ll need to set that in the Facebook developer console.




Hope that helps!




Alex

**Comment by serv** [comment]
Thanks Alex. That's the response I was looking for.
