### ISSUE TITLE
No way to subscribe to realtime updates from another page

### ISSUE THREAD

**Issue by mberman84** [arsduo/koala#445]
I'm trying to subscribe to realtime updates from a page that I have an access token to. However, there doesn't seem to be a way to specify an access token for another page. It seems the only way to use koala realtime updates is to subscribe to things directly associated with your facebook app. This doesn't really make sense for most use cases though. 

Is there a way to subscribe to a page's conversations when that page isn't my app's page but rather a page I have access to?

**Comment by arsduo** [comment]
Hey there — sorry about the late response. Did you ever figure this out? This sounds first like a Facebook question — can you actually do that with the API? (For instance, using the Graph API Explorer.)

If so, and if you can't do it with Koala, if you can post the call you make in the explorer and what you tried with Koala, and I can figure out the right code changes to make it possible.

Thanks!

**Comment by arsduo** [comment]
Resolving from it's been a while. Let me know if it's still an issue!
