### ISSUE TITLE
call-to-action button for posted item

### ISSUE THREAD

**Issue by przbadu** [arsduo/koala#448]
Hi, I am posting created product to facebook which is successful....now I want to add `call-to-action` button on that posted product to facebook, something like  `buy now` or `shop now` button.

Did anyone have used `call to action` button with koala gem? 

Here is what I am doing to post product to facebook:

``` ruby
    response = graph.put_connections(self.uid, 'feed', {
      'name' => product.name,
      'link' => "#{ENV['PROTOCOL']}#{ENV['HOSTNAME']}/#{self.id}/timelines",
      'picture' => product_picture_url,
      'description' => product.description
    })

    product.update_attribute :uid, response['id']
```

Is it possible to add `call-to-action` button for posting product or we can only add `call-to-action` button in ads?

Thanks

**Comment by arsduo** [comment]
Apologies for the late response! I'm sure you've figured something out by now, but tl;dr: I'm not sure. [facebook.stackoverflow.com](http://facebook.stackoverflow.com) is a good place to ask questions about the Facebook API itself (I only know sections of it). 

Closing this issue, feel free to reopen is there's anything that would be good to change in Koala around this.
