### ISSUE TITLE
get_objects returns hash, not array

### ISSUE THREAD

**Issue by dsims** [arsduo/koala#455]
The code description says it "returns an array of object data hashes", but it is instead returns a hash of object data hashes with the object ids as keys.

This is not consistent with when you don't pass in any ids and it returns an empty array.

**Comment by arsduo** [comment]
Hey there — sorry about the late response. Can you provide an example of this (with Koala's debug mode turned on)? Looking through the API docs again it looks like it's still returning arrays, so I'm wondering if it's something very specific.

Thanks!

**Comment by arsduo** [comment]
Closing since it's been a while. Please reopen if you're still encountering it!
