### ISSUE TITLE
Friends is returning all FB friends, not just Friends who also connected app to FB

### ISSUE THREAD

**Issue by chhhris** [arsduo/koala#459]
I've installed `gem "koala", "~> 2.0"` and `gem 'omniauth-facebook',  '~> 2.0.1'`

I authenticate via omniauth-facebook and initialize Koala using the `oauth_access_token` that I got back.
```
@graph = Koala::Facebook::API.new(@user.services.facebook.first.oauth_access_token)
```
Then when I try to grab friends, from FB's documentation I expect to only receive friends who have also connected to my app, however I receive back my entire friends list.
```
@graph.get_connections("me", "friends")
@graph.get_connections(@user.services.facebook.first.uid, "friends")
@graph.get_connections(@user.services.facebook.first.uid, "friends", api_version: "v2.0")
```
All three methods return my entire friends list. Not what I'm expecting. Did I miss something in my configuration?

**Comment by monteirobrena** [comment]
When your app was created in Facebook?

**Comment by arsduo** [comment]
Hey — did you ever figure out the issue? It sounds more like an FB API version problem than a Koala one, but I'd be curious to hear if you ever solved it. (I'm going to resolve the issue, but please reopen if it turns out to be a Koala bug.)
