### ISSUE TITLE
Override logging for a certain section/module in the application

### ISSUE THREAD

**Issue by pratik60** [arsduo/koala#460]
Hi All, 

In our config/initializers ...., we do have Koala::Utils.level = Logger::DEBUG unless Rails.env.production?. But there's a particular file where we definitely want to enable debug even on production, what is the best way to do that, as its a beta feature and we want to log all requests? 

Is that possible? If so, how?

**Comment by bnorton** [comment]
There is currently no way to do this with the current config and logger setup. My suggestion is to submit a pull request that adds a silencer:

```ruby
Koala::Utils.silence do
  # silenced use of Koala
end
```
