### ISSUE TITLE
Fanpages - Creating Fanpages to Testing Users

### ISSUE THREAD

**Issue by rafaelcgo** [arsduo/koala#461]
How can I accomplish this? I've been looking through the Koala Docs and couldn't figure it out.

Is there a way to create users who have fanpages they manage, in order to test posting to the fanpage?

**Comment by arsduo** [comment]
Apologies for the late response, the issue backlog grew and I missed some. I don't know the answer to this (and assume you figured something out), but [facebook.stackoverflow.com](http://facebook.stackoverflow.com) is a great resource in general.
