### ISSUE TITLE
Is Koala thread-safe?

### ISSUE THREAD

**Issue by mattdipasquale** [arsduo/koala#463]
I'm wondering how I should [configure Puma on Heroku](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server).

**Comment by bnorton** [comment]
Really this is a combination question of if the library itself is thread safe and if `Faraday` is as well. As per the discussion (https://github.com/lostisland/faraday/issues/126) it seems that `Faraday` is assumed to be thread safe. As for the Koala library, I can find no obvious evidence that it is **not** thread safe.

Some background is that we have run Koala in production with up to 80 sidekiq threads all contacting the Facebook API from one process without issue.

**Comment by arsduo** [comment]
Koala is thread-safe in itself -- it's pretty simple and doesn't do anything that would cause concurrency issues. The only possible vector for problems would be in the libraries it uses; as @bnorton points out, Faraday is thread-safe. MultiJson appears to be thread-safe as well, though I can't find an explicit statement to that effect.

Overall, I've never encountered problems or heard of anyone having problems, and Brian's experience is a good confirmation that Koala can be used in a multi-threaded environment.
