### ISSUE TITLE
delete_object() does not honor api_version override

### ISSUE THREAD

**Issue by lapygithub** [arsduo/koala#467]
The following code didn't hit FB API v2.3:

``` ruby
fb  = Koala::Facebook::API.new(oauth_token)
fb.delete_object(id, {api_version: "v2.3"})
```

While calling via fb.api does:

``` ruby
r = fb.api("/#{id}", {}, "delete", {api_version: "v2.3"})
```

Found this issue because permissions errors (publish_actions required) were being thrown while trying to remove comments from a page.  Our app was granted manage_pages and publish_pages which allows delete, but not from v2.0.  (Didn't test v2.1 or v2.2 in case anyone is wondering)

**Comment by alexandrule** [comment]
The same for me. I can't delete application.

facebook = Koala::Facebook::API.new(oauth_token)
facebook.delete_object(facebook_user_id)

Koala::Facebook::ClientError: type: OAuthException, code: 100, message: (#100) Can only call this method on valid test users for your app [HTTP 400]

Works only like this:
curl https://graph.facebook.com/facebook_user_id/permissions?method=delete&access_token=access_token

**Comment by lapygithub** [comment]
Hello Alex-

More than likely your exception can be fixed by checking on the page and/or oauth token you are using.
The error message seems to indicate that you are trying to use a test app token on a live user page.
I don’t think it has to do with overriding the FB API version as my issue text describes.

Regards,
-Mike
Michael Lapinskas
Senior Director Platform Architect
[p.] +1 415.295.2587 | mlapinskas@appen.com | @lapytweet
Appen | www.appen.com<http://www.appen.com/> | Visit us on Facebook<http://www.facebook.com/AppenInc>

**Comment by alexandrule** [comment]
Hi Mike (@lapygithub) 

Thanks for your response.

I checked and works only like this: 

<pre>
facebook = Koala::Facebook::API.new(oauth_token)
facebook.api("me", {}, "delete")
</pre>

**Comment by arsduo** [comment]
Hey Mike,

Sorry about the late response — are you still seeing this issue? The API version is set in Koala's HTTPService module, through which all API requests go, so if the version weren't working it seems like it would break for all requests.

If you're still seeing it, could you try turning on Koala's debug mode and seeing whether the gem is sending through the correct version in the string? If not, if you can post the details it gives here and I can look into it.

Thanks!

Alex

**Comment by lapygithub** [comment]
Hello Alex-  I don't have a good way to test this again without a lot of work as I basically pushed to prod until I found something that worked. (FB test apps don't allow configured permissions...)

Not sure about the service module as this was only call I tried applying the versioning to.
If it helps, initialization was set like this:
	Koala.config.api_version = 'v2.0'

and here is the function I'm using to delete with (commented out the non-working method) :
	def remove_fb_object(oauth_token, id)
		begin
			fb  = Koala::Facebook::API.new(oauth_token)
			$log.debug("********* id=#{id} - Before Delete")
			r = fb.api("/#{id}", {}, "delete", {api_version: "v2.3"})
			# For some reason this Koala 2.0.0 call doesn't really use v2.3 as it doesn't work!
			# fb.delete_object(id, {api_version: "v2.3"})
			$log.info("********* id=#{id} - delete object result: #{r}")
		rescue => e
			drops = ""
			e.backtrace.drop(1).map{|s| drops << "\t#{s}\n"} if !e.backtrace.drop(1).nil?
			$log.error "facebook:remove_fb_object: Problem connecting to Facebook:id=#{id}\n   #{e.backtrace.first}: #{e.message} (#{e.class}), #{drops}"
			return false
		end
		return true
	end

Regards,
-Mike

**Comment by arsduo** [comment]
Hi Mike! Apologies for the late response. Since it sounds like you found a way to resolve this and I haven't heard other reports of this, I'm going to close this. Please reopen if appropriate!
