### ISSUE TITLE
Which permissions required to post to a page as a page

### ISSUE THREAD

**Issue by bradical** [arsduo/koala#470]
I'm a little confused about which permissions are required and which endpoints Koala is using to do this. I'm currently using the following to get a client:

```ruby
  def client
    @client ||= Koala::Facebook::API.new(self.access_token, <our_secret>)
  end

  def page_client
    return @page_client if defined?(@page_client)
    token = page_access_token
    if token
      @page_client = Koala::Facebook::API.new(token, <our_secret>)
    else
      @page_client = nil
    end
  end
  def page_access_token
    c = self.client
    return unless c
    account = c.get_object('me/accounts').detect { |account| account["id"] == facebook_page_id.to_s }
    account["access_token"] if account
  end
```

We're requesting `manage_pages` and `publish_pages` which I believe is all that is needed to post to a page.

Yet, when I do:

```ruby
 page_client.put_wall_post(text)
```

I'm getting: "type: OAuthException, code: 200, message: (#200) The user hasn't authorized the application to perform this action [HTTP 403]" even though my app is approve for both `manage_pages` and `publish_pages`

Any ideas? I read some stuff about `publish_stream` but I'm not seeing that perm anymore and it doesn't appear to be necessary for publish to pages anyway.

**Comment by bradical** [comment]
I found the Koala logging utilities and it appears to be this request that is failing:

```
POST: /me/feed params: {"message"=>"Testing posting with Koala and some new permissions", "access_token"=>"[Redacted]", "appsecret_proof"=>"[Redacted]"}
```
but I've verified that:

- Our app requests the publish_pages permission
- The app is correctly authorized on my account
- The access token is indeed the page access token as opposed to my user token.

I'm happy to escalate this to Facebook if it seems like the issue is likely on their end. I just can't quite tell at this point.

**Comment by bradical** [comment]
Believe we isolated this problem to not setting an explicit api version. Once we added:
```
Koala.config.api_version = 'v2.3'
```
our app started working again.

**Comment by zealot128** [comment]
Thanks for posting that! I was looking into that problem half of the day and could not figure out why it wouldn't work :dancer: 

Confirming it even works with ``api_version = 'v.2.4'``.

**Comment by iashanmugavel** [comment]
Hi,

I am getting this error while sharing any post in facebook wall. 

`type: OAuthException, code: 200, message: (#200) The user hasn't authorized the application to perform this action [HTTP 403]`

other than `Admin`, it is throwing the above error. 

Do I really need to get permission from facebook for publishing any content in facebook wall?

**Comment by zealot128** [comment]
Yes, Facebook changed that a while ago.
You need to apply with the submission process in Facebook... You have to explain for each permission what you application does with it. You will also need a test account, so a Facebook employee can test the feature by themself.... :hankey: Good luck!

**Comment by iashanmugavel** [comment]
Thanks. In my application, it has a lot of subdomains (around 55), each subdomain has its own custom domain. For this case, do I need to create separate facebook app for each subdomain? can't I manage all subdomains and custom domains in single facebook app? 


For E.g:

`www.example.com` - actual domain

It has a lot of subdomains,

`abc.example.com` - its custom domain - `abc.com`

`cde.example.com` - its custom domain - `cde.com`

`xyz.example.com` - its custom domain - `xyz.com`
