### ISSUE TITLE
Nested objects don't work with Koala (Ads API)

### ISSUE THREAD

**Issue by danteoh** [arsduo/koala#473]
The Facebook Ads API supports application/json.  The gem should probably support it as well, as some requests that are ads api related don't work.

For example, multi-link/multi-product page posts don't work as the gem doesn't format nested child_attachments properly.  

I submitted pull request https://github.com/arsduo/koala/pull/472 to support a proper Faraday JSON request which solves this issue.

Let me know if you need me to change anything else or if anyone else has additional feedback on this.

**Comment by pratik60** [comment]
We used to format this as a json, and explicitly send it. This would be great.

**Comment by arsduo** [comment]
This has been merged!
