### ISSUE TITLE
Mocking a batch call in rspec

### ISSUE THREAD

**Issue by pratik60** [arsduo/koala#476]
To mock a single call of changing the status of , I do something like this

```
  before(:each) do
    @facebook = double("Koala")
  end

  it "Campaign rule triggers" do
    ....
    expect(@facebook).to receive(:put_object).with(campaign_id, nil, campaign_group_status: 'PAUSED') { { "success" => true } }
    ......
  end
```

but to mock a batch call which would be changing the status of 50 campaigns, I have no idea what the syntax would look like. 

```
  def toggle_campaign_status(fb_campaign_ids, status_type)
    fb_campaign_ids.each_slice(50) do |campaign_ids_50|
      fb.batch do |batch_api|
        campaign_ids_50.each do |campaign_id|
          batch_api.put_object(campaign_id, nil, campaign_group_status: status_type) do |data|
            begin
              if data['success'] == true
                .......
              end
            rescue
              .......
            end
          end
        end
      end
    end
  end
```

Any help will be appreciated, absolutely stuck on mocking a batch call....Any available examples  will help

**Comment by pratik60** [comment]
@arsduo Any idea?

**Comment by arsduo** [comment]
Hey there,

Sorry about the delay in getting back to you. I know it's probably too late, but in case you still need help (or someone else does), I have a couple of ideas.

My first thought was that you could mock the API a bit:

```
mock_batch_api = object_double(api)
allow(api).to receive(:batch).and_yield(mock_batch_api)
```

but that still leaves you with the trouble of testing all the possible responses.

The best suggestion would be to separate out your method into several components:

```
def toggle_status_for_multiple_campaigns(fb_campaign_ids, status_type)
  fb_campaign_ids.each_slice(50) do |campaign_ids_50|
    batch_api = fb.batch do |batch_api|
      campaign_ids_50.each do |campaign_id|
        update_campaign_status(batch_api, campaign_id, status_type)
     end
  end
end

def update_campaign_status(batch_api, campaign_id, status_type)
  batch_api.put_object(campaign_id, nil, campaign_group_status: status_type) do |data|
            begin
              if data['success'] == true
                .......
              end
            rescue
              .......
            end
          end
end
```

That way, you can test the update_campaign_status method individually with a single test double, make sure all aspects work properly. 

Then with the toggle_status_for_multiple_campaigns method, you just have to test that it passes through the ids in groups of 50 (e.g. use "Rspec's ability to yield different objects on subsequent calls":https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/yielding#yield-multiple-times, and verify that the update method gets called with the right test double for whichever block of 50 is appropriate).

Hope this helps! Let me know if you have any additional questions.

**Comment by pratik60** [comment]
@arsduo Hey, thanks for replying even though its super late. Believe it or not, it stands to be the one of the prominent untested code in our platform :-(

Assuming, we go with even the first approach

```
oauth_token = "token123"
api = Koala::Facebook::API.new(oauth_token)
mock_batch_api = object_double(api)
allow(api).to receive(:batch).and_yield(mock_batch_api)
```

How would I actually simulate/mock the result, in this case [{"success" => "true"}, {"success" =>"true"}]  as this is executed over two campaigns in our test case?

**Comment by dspoonia7** [comment]
Would like to know this as well....

```
api.batch do |batch_api|
      batch_api.put_object(@adset.ad_set_id.to_s, nil, campaign_status: 'ACTIVE') { { "success" => true }}
end
```

Tried the above but didn't work.

**Comment by tomzilla** [comment]
same
