### ISSUE TITLE
Response headers in exceptions

### ISSUE THREAD

**Issue by runa** [arsduo/koala#477]
Hey, I'm debugging some requests and I would love to have the `fb-trace-id` response header in the exception thrown when the request fails.

Would you accept a patch for this?

Thanks

**Comment by arsduo** [comment]
Definitely! If you submit a pull request I'd be happy to merge that in.

It looks from lib/koala/http_service/response.rb like the HTTPService::Response object does expose the headers -- perhaps it would be as simple as adding the `fb-trace-id` (and/or perhaps the entire response object) to Koala::Facebook::ServerError.

I'll close this issue -- once you have a PR ready (with tests) go ahead and open it up and we'll get it into the library.

Thanks!
