### ISSUE TITLE
Make HTTPService a class

### ISSUE THREAD

**Issue by arsduo** [arsduo/koala#480]
HTTPService is a bit of a mess. It works and is tested, but has two major design flaws:
- Many of the methods are way too long and should be broken up into small, single-purpose, easy-to-read functions
- Since all methods are class methods, there's a huge amount of info being passed around repeatedly as arguments (which would get even worse as the methods are broken up)

Both of these could be addressed by making HTTPService a class. For ease of implementation and compatibility, we should keep the `HTTPService.make_request` class method as an entry point; it, however, would instantiate an HTTPService object, which would make the actual request and handle/package the response.

An additional minor design flaw is that the `encode_params` method is used directly by the OAuth class; it should be moved to Koala::Utils.

This is a purely internal class, but since it would change a few publicly-facing methods, it will probably be released as version 3.0.

**Comment by vhoof** [comment]
I can take a look at this over the next couple of days.

**Comment by arsduo** [comment]
Thanks! Let me know if you have any questions. I appreciate your jumping in
on several of these issues.

2015-08-02 16:36 GMT-05:00 Bryan Vanderhoof <notifications@github.com>:

**Comment by arsduo** [comment]
Looking back at this having done more programming in functional and immutable languages, I actually prefer it not to be a class. By extracting a Request object from HTTPService, it turns out we can simplify the module a lot without having to add state.
