### ISSUE TITLE
TestUser#delete "Unsupported delete request"

### ISSUE THREAD

**Issue by nxvl** [arsduo/koala#484]
When performing delete(test_user_id) on TestUser, the script crashed with:

```
GraphMethodException, code: 100, message: Unsupported delete request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api [HTTP 400]
```

**Comment by gkop** [comment]
I can replicate this with plain HTTP - I think it's a bug on Facebook's end.

**Comment by arsduo** [comment]
Did you ever figure this out? I'm not sure what the right answer is, unfortunately. [facebook.stackoverflow.com](http://facebook.stackoverflow.com) is a good place to ask.

**Comment by arsduo** [comment]
Resolving since it's been a while. Let me know if it's still an issue.
