### ISSUE TITLE
Mention user/page when posting w/ graph.put_connections()

### ISSUE THREAD

**Issue by wfhio** [arsduo/koala#486]
Hi All,

Apologies if this is not the right forum to ask questions, but the google group seems dead.  I have a background job that posts updates to my _own_ Facebook page and that all appears to be working fine.  What I would like to do is mention a user in the message, which I believe can be done using @[user-id] or @[page-id].  I've read threads saying that no longer works, while others say it should.  Is anyone able to confirm if this is possible w/ koala and if there is anything I need to do on Facebook's site to allow this to work?

Thanks!

--Matt

**Comment by Skeyelab** [comment]
I also cannot get it to work.  @wfhio , did you ever figure this out?

**Comment by wfhio** [comment]
Nope @Skeyelab, I never did figure this one out.  :(

**Comment by Skeyelab** [comment]
Then how will I ever make my app that taunts my friend as to how bad the Cardinals are doing compared to the Cubs ;)

**Comment by arsduo** [comment]
That's a good question, but unfortunately I don't know :/ I suggest asking on facebook.stackoverflow.com (if it's still an issue — apologies for the late response!).
