### ISSUE TITLE
Facebook API 2.4

### ISSUE THREAD

**Issue by FCasanova** [arsduo/koala#487]
Hello! How does Koala support Facebook's newest API 2.4? What should I change in my code and how do I use the new functionalities?

**Comment by arsduo** [comment]
Koala is API version-agnostic -- you should just be able to set the version number and make the right type of API calls (e.g. put/delete/get/etc. and for an individual object, a connection, etc.). If you encounter any types of calls that can't be done with the existing API methods, let me know (just file another ticket).

Thanks for using Koala!

**Comment by FCasanova** [comment]
Thank you! I'll update my app to incorporate these new API funcs and I'll let you know if I have any trouble.

Btw, nice job! Koala is great

**Comment by arsduo** [comment]
Thank you! I appreciate that. Good luck with your app, and let me know if
you encounter any issues using Koala with the new API version.

2015-08-28 14:33 GMT-05:00 FCasanova <notifications@github.com>:
