### ISSUE TITLE
I could not get any friends 

### ISSUE THREAD

**Issue by poc7667** [arsduo/koala#489]
```
  [6] pry(User)> @graph = Koala::Facebook::API.new(auth[:credentials][:token])
  #<Koala::Facebook::API:0x007ff3d9a5c2b8 @access_token="CAAW45iRdsFzjRA6H9YuAp7VqRD", @app_secret=nil>
  [7] pry(User)> profile = @graph.get_object("me")
  {
                "id" => "1135695",
             "email" => "poc7@gmail.com",
            "gender" => "male",
              "link" => "https://www.facebook.com/app_scoped_user_id/sadas/",
            "locale" => "en_US",
              "name" => "",
          "timezone" => 8,
      "updated_time" => "2015-08-20T08:11:37+0000",
          "verified" => true
  }
  [8] pry(User)> friends = @graph.get_connections("me", "friends")
  []
```

**Comment by bowekr** [comment]
same problem here.
get_connections "me" friends likes or other always return empty array

**Comment by simoncorreaocampo** [comment]
Hi, After facebook API v2, you should use graph.get_connections("me", "taggable_friends") instead of graph.get_connections("me", "friends")

**Comment by Linell** [comment]
I tried `@graph.get_connections("me", "taggable_friends")` as well and just got an empty array.

**Comment by djmolny** [comment]
Make sure that your OAuth scope includes the 'user_friends' permission -- see: https://github.com/mkdynamic/omniauth-facebook.

Next, de-authorize the app by visiting https://www.facebook.com/settings?tab=applications then add it back again. You should get the authorization pop-up window and the list of permissions should include access to your friends.

**Comment by The-Penultimate-Defenestrator** [comment]
Somebody pointed out the title of this on Twitter https://twitter.com/penmanross/status/695417135670005761

**Comment by arsduo** [comment]
Thanks simoncorreaocampo and @djmolny for providing advice! 

@poc7667, @bowekr, @Linell -- did looking at the permissions you requested help solve your problem? If not, let's figure out what permissions your token does have and try to get to the bottom of this.

**Comment by vladvict** [comment]
Sometimes it can be the case when permissions in scope are correct and it is more than just website in Facebook app (iOS, Android etc.), it will be necessary to set extra permissions on their SDK.

**Comment by arsduo** [comment]
Since it doesn't sound like there's anything specific to Koala in here, I'm going to close it. Please reopen if there are some things we can change/fix/improve in the gem!
