### ISSUE TITLE
NameError: uninitialized constant

### ISSUE THREAD

**Issue by saigkill** [arsduo/koala#491]
Actually i try to post on my wall with that code:

@graph = Koala::Facebook::API.new(mytoken) #my generated token
profile = @graph.get_object('me')
friends = @graph.get_connections('me', 'friends')
@graph.put_connections('me', 'feed', message: 'Testmessage from the Graph API')

But sadly i'm getting an NameError.
Can i fix this?

**Comment by arsduo** [comment]
Hi! Sorry about the late response -- are you still having problems? Were you able to figure out what it was? If not: did you `require 'koala'` somewhere in your code? Can you provide the full error message for the `NameError`?

Thanks for using Koala! Let me know if I can help with anything.

**Comment by arsduo** [comment]
Closing since it's been a while. Please reopen if you're still encountering it!

**Comment by surendar1161** [comment]
NameError (uninitialized constant Koala::Facebook::GraphAPI)    this is the full error @arsduo
