### ISSUE TITLE
Marketing API

### ISSUE THREAD

**Issue by phlegx** [arsduo/koala#492]
Facebook also offer s a Marketing API: https://developers.facebook.com/docs/marketing-apis?locale=de_DE

As far as I have seen, Koala doesn't support that yet. Are there any plans to add support for the Marketing API in the near future?

thanks!

**Comment by arsduo** [comment]
Servus!

Koala does support the Marketing API (and I believe a number of other
people are using it). Koala doesn't have specific modules for different
parts of the Facebook API, but rather matches the *shape* of the Graph API
-- the way individual objects connect to other objects.

So for instance, these two examples from the Graph API documentation would
be done like this:

https://graph.facebook.com/
<API_VERSION>/act_<AD_ACCOUNT_ID>?fields=id,name,objective
=> `api.get_connection("act_#{account_id}", fields: ["id", "name",
"objective"])`
https://graph.facebook.com/<API_VERSION>/<CAMPAIGN_ID>
=> `api.get_object("act_#{campaign_id}")`

See the Koala documentation for info on the API version and for the other
methods (put_object, etc.)

Good luck!

2015-09-09 5:35 GMT-05:00 Phlegx Systems OG <notifications@github.com>:

**Comment by phlegx** [comment]
Servus arsduo :-)

Thanks a lot for the info, I will have a look at this!

best 
Martin

**Comment by giedriusr** [comment]
@phlegx I think this can be closed.
