### ISSUE TITLE
Extremely slow on first request

### ISSUE THREAD

**Issue by silasjmatson** [arsduo/koala#493]
Given the following bit of code:

``` ruby
def timeit(graph)
  beginning = Time.now
  graph.get_object("me", fields: "id")
  ending = Time.now
  ending - beginning
end

graph = Koala::Facebook::API.new("<API_KEY>")
```

`timeit` takes an insanely long time (up to 90 seconds), on the first request, but subsequent requests are only a few tenths of a second.

Is there some configuration I'm missing? Do I have to specify the API Version? Is this Facebook or Koala? Is there caching involved?

**Comment by silasjmatson** [comment]
The same request using Facebook's Graph Explorer is always fast.

**Comment by silasjmatson** [comment]
On the same machine, same network, `curl` requests are always fast as well.

**Comment by silasjmatson** [comment]
Different network, requests are fast as well. It's looking like a network issue, but I'm not sure why there would we a difference between Koala and curl on the same network.

**Comment by sailing** [comment]
Could be authenticating differently on the first request.

**Comment by arsduo** [comment]
Hmm, that's strange. Are you still seeing this?

(Apologies for the really late response!)

**Comment by arsduo** [comment]
Resolving since it's been a while. Let me know if it's still an issue.
