### ISSUE TITLE
No option to specify version for get_connection call

### ISSUE THREAD

**Issue by rahul1990gupta** [arsduo/koala#494]
Hi, 
I was moving my app to v2.4 one piece at a time. I did that specifying get_object calls 
@graph.get_object("me", {}, api_version: "v2.0")
but couldn't do the same for get_connections calls ?

Any suggestion on how to make get_connection call with specified version ?

**Comment by arsduo** [comment]
That's odd — every request in Koala supports the options hash that includes api_version. Apologies for the late response, are you still experiencing this?

**Comment by arsduo** [comment]
Since it's been two weeks I'm going to close this, but if you are still having the issue, definitely reopen this or create a new issue with that info. Thanks!
