### ISSUE TITLE
get_object returns different hash for different users

### ISSUE THREAD

**Issue by adisos** [arsduo/koala#497]
Is it on facebook part or something else?

Anyway, I think it would be good if you edit `get_object` examples to explicitly define extra option `fields`

For example,

```
@profile = @graph.get_object("me", fields: 'id,name,email,gender,link,locale,timezone,verified')
```

**Comment by arsduo** [comment]
Hi! Apologies for the late response. That definitely sounds like it was a Facebook issue — hopefully it's worked itself out. If not, [facebook.stackoverflow.com](http://facebook.stackoverflow.com) is a good place to ask questions about the Facebook API.

Thanks for using Koala!
