### ISSUE TITLE
Batch 'next_page' for all data on an edge?

### ISSUE THREAD

**Issue by mfclarke** [arsduo/koala#498]
Is it possible to use the batch_api to fetch all data for an edge? Like for example, the "likes" edge of the "me" object? I can of course do this without batching, by calling ```next_page``` until no data comes back. But batching so it's all just 1 API request I can't get the syntax right for. As far as I can tell you can't just get "all" the pages either, you'd have to chain as many batch calls together as your upper limit. Any ideas?

Thanks

**Comment by arsduo** [comment]
Hmm, I don't think there's an easy way to do that. Facebook returns specific URLs for next_page and previous_page, so there doesn't seem to be a way to get at the next information before the previous value is found. 

That said, there might be a complicated way to do that -- Facebook allows you to [specify dependencies for batch API calls](https://developers.facebook.com/docs/graph-api/making-multiple-requests#operations) and to reference info from one call in another. I've never really used it myself, but perhaps you could construct a request that does it. (If you figure it out, let me know!)

Good luck! Let me know if I can help with anything else.
