### ISSUE TITLE
get_connections page name != page slug

### ISSUE THREAD

**Issue by danielbonnell** [arsduo/koala#500]
Hello,

I don't know that this is a bug necessarily, but I'm wondering if there is a way to get a page's slug, which may be different than the name if there are spaces in the name. For example, if I have a test page called `Verified Analytics Inc`, the name returned by `get_connections` is `Verified Analytics Inc`, but the slug of the page is `verified.analytics.inc`. Is there a reliable way to get the page slug of a page or am I stuck using the page ID for pages with complicated names?

Thanks!

**Comment by arsduo** [comment]
Apologies for the late response! I'm sure you've figured something out by now, but tl;dr: I'm not sure. [facebook.stackoverflow.com](http://facebook.stackoverflow.com) is a good place to ask questions about the Facebook API itself (I only know sections of it). 

Closing this issue, feel free to reopen is there's anything that would be good to change in Koala around this.
