### ISSUE TITLE
Facebook Graph Calls Fail if IPV6 is Enabled

### ISSUE THREAD

**Issue by elbarsal** [arsduo/koala#501]
This is actually a Facebook problem, but maybe it can be documented somewhere here for Koala users, I spent hours trying to figure things out and I'd like to save others their time.

It seems that the Facebook graph API fails if IPV6 is enabled on your source machine - so doing something like this:

curl -X GET https://graph.facebook.com/v2.5/{UID REDACTED}/permissions?access_token={TOKEN REDACTED}

returns an empty set - which is the result of graph.get_connections('me', 'permissions') - and then also causes other things to fail.

We solved our problem by turning off IPV6 on our servers - and it is clearly a Facebook issue - but maybe this can help somebody else out.

**Comment by arsduo** [comment]
That's really fascinating! If this is still happening you should definitely file a bug with Facebook. Thanks for filing this issue -- it'll be useful to have it here for others who encounter it. (I'll close it since there's nothing specific to do, but it'll still be searchable.)
