### ISSUE TITLE
Facebook Graph return [] on rails 4

### ISSUE THREAD

**Issue by manat129** [arsduo/koala#503]
Need advise,..

I have a rails application that using omniauth and koala. i have follow instruction to use koala gem, but it seem some thing wrong with my code, hopefully someone can give me an answer.

i put method 

``` ruby
class User < ActiveRecord::Base
  has_many :facebook_friends

  def friendlist
    if facebook { |fb| fb.get_connections("me", "friends")}
      facebook { |fb| fb.get_connections("me", "friends")}.each do |friend|
        self.facebook_friends.find_or_create_by(:name => friend['name'], :uid => friend['id'])
      end
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token, Settings.facebook.app_secret)
    block_given? ? yield(@facebook) : @facebook
  rescue Koala::Facebook::APIError => e
    logger.info e.to_s
    nil
  end
end
```

and call this method when i'm outhenticated user when using omniauth, but the result return [], please give me an advise

**Comment by arsduo** [comment]
Hi! Were you able to figure this out? Sorry about the delayed response.

One really useful technique for debugging FB calls is the [Facebook Graph API Explorer](https://developers.facebook.com/tools/explorer/). If you're getting unexpected results back from FB calls, you can use the access token you get back to run requests through your browser. (Often that helps catch permissions issues or other strange things.)

That looks to me like it should work overall, though it's worth noting that the first `facebook { |fb| fb.get_connections("me", "friends")}` will always return true (in Ruby empty hashes and arrays are truthy). A better approach would be something like this:

```ruby
friends = facebook { |fb| fb.get_connections("me", "friends")}
if friends.length > 0
  friends.each { ... }
end
```

Let me know if you still have any questions. Good luck!

**Comment by arsduo** [comment]
Resolving since it's been a while, let me know if you still have issues!
