### ISSUE TITLE
Update docs to show how to set timeouts

### ISSUE THREAD

**Issue by szimek** [arsduo/koala#504]
We had a strange and rather unpleasant issue where requests to Facebook would just hang indefinitely and block our servers. Turns out that in Ruby 2.2.x `Net::HTTP#open_timeout` by default is set to `nil` (in 2.3 it was fortunately changed to 60 seconds).

We tried setting `http_options` like this:
```ruby
Koala.http_service.http_options = {
  timeout: 5,
  open_timeout: 2
}
```
but it turns out that it's supposed to be set like this:
```ruby
Koala.http_service.http_options = {
  request: {
    timeout: 5,
    open_timeout: 2
  }
}
```
which we figured out by looking at [this](https://github.com/arsduo/koala/blob/master/lib/koala/http_service.rb#L151) line. Minor difference, but showing it in docs could save others some time. It would be enough if the docs just showed how to set `timeout` option, because `open_timeout` is specific for `net_http` adapter.

**Comment by nonmadden** [comment]
I think so

**Comment by arsduo** [comment]
That's a good idea -- the Faraday stuff can be a bit confusing. I've added some [documentation of how it works as of Faraday 0.9.1](https://github.com/arsduo/koala/wiki/HTTP-Services#ssl-proxy-timeout-and-other-faraday-options). Thanks!
