### ISSUE TITLE
Set minimum version of MultiJson dependency to 1.3.0

### ISSUE THREAD

**Issue by andreas-venturini** [arsduo/koala#506]
The load/dump api was introduced in MultiJson version [1.3.0](https://github.com/intridea/multi_json/blob/master/CHANGELOG.md#130). However, koala does not specify a minimum version of the the MultiJson dependency. If dependencies in other gems lock MultiJson to < 1.3.0 koala will fail (MultiJson will throw a `MultiJson::LoadError` in this case).

**Comment by arsduo** [comment]
Good catch! I'll bump up the requirement in the next release.
