### ISSUE TITLE
Trouble with RealtimeUpdates#validate_update 

### ISSUE THREAD

**Issue by mwpastore** [arsduo/koala#508]
I'm struggling to get a Facebook webhook working. I've tried manually computing the sha1 hexdigest of the payload and comparing it to X-Hub-Signature, with and without unicode-escaping, and that didn't work. Now I'm trying to use Koala::RealtimeUpdates#validate_update and that's not working either. It's a simple Rack/Sinatra app with no other middleware. The Facebook app ID and secret are valid and correspond to the app that owns the webhook, but I'm seeing a 401 response to Facebook's request in my logs. Any suggestions?

```ruby
helpers do
  def oauth
    @oauth ||= Koala::Facebook::OAuth.new \
      ENV['FACEBOOK_APP_ID'],
      ENV['FACEBOOK_APP_SECRET']
  end

  def updates
    @updates ||= Koala::Facebook::RealtimeUpdates.new \
      :app_id => oauth.app_id,
      :secret => oauth.app_secret,
      :app_access_token => oauth.get_app_access_token
  end
end

get '/facebook/user', :provides => :json do
  Koala::Facebook::RealtimeUpdates.meet_challenge params, ENV['FACEBOOK_WEBHOOK_USER_TOKEN']
end

post '/facebook/user', :provides => :json do
  halt 401, 'Not Authorized' \
    unless updates.validate_update request.body, headers
```

**Comment by arsduo** [comment]
I'm about to get on a long flight, but I plan to dig into my Koala backlog
this weekend — I'll get back to you then!

**Comment by mwpastore** [comment]
Thanks Alex. Have a safe flight!

**Comment by mwpastore** [comment]
Duh, it's `env`, not `headers`. D'oh!
