### ISSUE TITLE
 intermittent returning type to /page/videos

### ISSUE THREAD

**Issue by faustoct** [arsduo/koala#509]
I'm calling fb api this way

`batch_api.get_connections("#{fb_page['fb_id']}", "videos?fields=description,created_time,permalink_url,format,from,source,title&limit=5&type=uploaded")
`

When I try to access data["title"] it gives me string sometimes an array. How can I fix it?

**Comment by faustoct** [comment]
I did a workaround
      ```
 if r["title"].class.kind_of? Array.class
         if r["title"].nil?
           title = r["description"]
         else
           title = (r["title"][0].nil? ? r["description"] : r["title"][0])
         end
       else
         title = r["title"]
       end
```

Any way. It's not very reliable to trust in a solution like that. Assuming the returned data will never change.

**Comment by arsduo** [comment]
Yeah, that's unfortunate. Unfortunately Facebook is responsible for the returned data -- if you're still seeing inconsistencies there, I'd recommend filing a bug with them. :|
