### ISSUE TITLE
How to pass the picture 'type' hash key in the fields?

### ISSUE THREAD

**Issue by nedpals** [arsduo/koala#519]
I know its sounds noobish but how do you pass the 'type' hash key of the picture to the fields mentioned in the **Getting Public Data** section of the [Graph API](https://github.com/arsduo/koala/wiki/Graph-API) page? I want to make the feed's image larger since I've tried the "get_picture_data" method but returns a code 12 error so I've decided to use this method to fetch it. Thanks in advance.

**Comment by ravuthlong** [comment]
access_token = auth['token']
	    facebook = Koala::Facebook::API.new(access_token)
	    facebook.get_object('me', fields: 'id,name,gender,picture.type(large)')


the documentation is terrible. took me an hour to find

**Comment by arsduo** [comment]
Yeah, that's no good. The picture convenience method should support that. I'll look into it and fix the bug. Thanks for reporting it (and apologies for the late response)!
