### ISSUE TITLE
Error after give permission: undefined method `synchronize' for nil:NilClass

### ISSUE THREAD

**Issue by nonato** [arsduo/koala#529]
I'm using koala version 2.3.0 + omniauth-facebook 3.0.0

I'm trying to do this:
**user_facebook_api = Koala::Facebook::API.new(user_facebook_token)
user_facebook_api.get_object("me")**

When I try in the console, it returns my profile correctly.

But on the server, it returns this
**.
**\* NoMethodError Exception: undefined method `synchronize' for nil:NilClass*
.**

what is wrong?

Already, thanks
# 

Full Trace of Server
/home/nonato/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/singleton.rb:139:in `instance'
multi_json (1.11.2) lib/multi_json/adapter.rb:21:in`load'
multi_json (1.11.2) lib/multi_json.rb:119:in `load'
koala (2.3.0) lib/koala/api.rb:89:in`api'
koala (2.3.0) lib/koala/api/graph_api.rb:527:in `graph_call'
koala (2.3.0) lib/koala/api/graph_api.rb:116:in`get_connection'
app/controllers/facebook_integrations_controller.rb:85:in `load_facebook_pages'
activesupport (3.2.18) lib/active_support/callbacks.rb:484:in`_run__122422330__process_action__648999105__callbacks'
activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.18) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
activesupport (3.2.18) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.18) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.2.18) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.18) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
activesupport (3.2.18) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.18) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (3.2.18) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.18) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
actionpack (3.2.18) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.18) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
actionpack (3.2.18) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.18) lib/abstract_controller/rendering.rb:45:in`process'
actionpack (3.2.18) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.18) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
actionpack (3.2.18) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.18) lib/action_dispatch/routing/route_set.rb:73:in`call'
actionpack (3.2.18) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.18) lib/action_dispatch/routing/route_set.rb:36:in`call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in`each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.18) lib/action_dispatch/routing/route_set.rb:608:in`call'
omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.3.1) lib/omniauth/strategy.rb:164:in`call'
omniauth (1.3.1) lib/omniauth/builder.rb:63:in `call'
exception_notification (4.1.1) lib/exception_notification/rack.rb:32:in`call'
actionpack (3.2.18) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.7) lib/rack/etag.rb:23:in`call'
rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/head.rb:14:in`call'
actionpack (3.2.18) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/flash.rb:242:in`call'
rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.7) lib/rack/session/abstract/id.rb:205:in`call'
actionpack (3.2.18) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.18) lib/active_record/query_cache.rb:64:in`call'
activerecord (3.2.18) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `_run__746720319__call__895200674__callbacks'
activesupport (3.2.18) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.18) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.18) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/reloader.rb:65:in`call'
actionpack (3.2.18) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
actionpack (3.2.18) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.18) lib/rails/rack/logger.rb:32:in`call_app'
railties (3.2.18) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.18) lib/active_support/tagged_logging.rb:22:in`tagged'
railties (3.2.18) lib/rails/rack/logger.rb:16:in `call'
request_store (1.2.0) lib/request_store/middleware.rb:8:in`call'
actionpack (3.2.18) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.7) lib/rack/methodoverride.rb:21:in`call'
rack (1.4.7) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.18) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
rack (1.4.7) lib/rack/lock.rb:15:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/static.rb:63:in`call'
rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
railties (3.2.18) lib/rails/engine.rb:484:in`call'
railties (3.2.18) lib/rails/application.rb:231:in `call'
rack (1.4.7) lib/rack/content_length.rb:14:in`call'
railties (3.2.18) lib/rails/rack/log_tailer.rb:17:in `call'
rack (1.4.7) lib/rack/handler/webrick.rb:59:in`service'
webrick (1.3.1) lib/webrick/httpserver.rb:138:in `service'
webrick (1.3.1) lib/webrick/httpserver.rb:94:in`run'
webrick (1.3.1) lib/webrick/server.rb:191:in `block in start_thread'

**Comment by arsduo** [comment]
Weird, that's very strange. Can you try upgrading to Koala 2.5.0rc1? That removes the dependency on MultiJson entirely.

**Comment by nonato** [comment]
Hello. thanks for response., I will try that and I will post the result.
thanks

**Comment by arsduo** [comment]
Closing since it's been 7 months — let me know if you're still seeing issues.
