### ISSUE TITLE
Latest JSON compliance

### ISSUE THREAD

**Issue by sakuro** [arsduo/koala#530]
The JSON gem has been updated and now are [RFC 7159 compliant](https://github.com/chottoda/json/blob/master/CHANGES.md#2015-09-11-200). MRI 2.4 [will bundle it](https://github.com/ruby/ruby/pull/1395).

We can remove some workaround codes [wrapping Facebook's responses in arrays](https://github.com/arsduo/koala/blob/master/lib/koala/api.rb#L87) then.

**Comment by arsduo** [comment]
Awesome! I really dislike those workarounds. I'll update the gemspec with 3.0 and remove those workarounds. Thanks for the heads-up!

**Comment by arsduo** [comment]
Hmm. Does it actually comply with the RFC? If I'm reading the [RFC](https://tools.ietf.org/html/rfc7159#page-13) properly, the string `"true"` is a valid JSON text, but `JSON.parse("true")` raises a `JSON::ParserError`. Facebook has returned those values in the past, which might require us to keep the hack. 

I'll open up an issue on the JSON gem (if no one else has) to ask this question.

**Comment by arsduo** [comment]
Ah! `quirks_mode: true` is my friend.

**Comment by arsduo** [comment]
Resolved in #573.
