### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by himberjack** [arsduo/koala#533]
Hi!

I suspect next_page is causing my program to have memory leak.
Please review:
http://stackoverflow.com/questions/38507256/potential-memory-leak-in-a-library

**Comment by bobber205** [comment]
Page no longer found for that SO post. 
we should close this issue.

**Comment by arsduo** [comment]
Yep! Thanks for flagging that @bobber205. @himberjack, if you find a replicable bug, please open another issue.
