### ISSUE TITLE
API Updates (Facebook Graph API  v2.0)

### ISSUE THREAD

**Issue by msroot** [arsduo/koala#535]
Hi

The Facebook Graph API  v2.0 will be deprecated on August 8, 2016. 
My question is this will affect koala's current version? 
We are using koala 2.0.0 atm.
 Is there a document that I can compare the koala version with the facebook graph version supported?

**Comment by kdelchev** [comment]
@msroot you can use github tags to compare different versions. Also check `changelog.md` for the relevant version changes. You should be able to upgrade koala to 2.1 and specify `Koala.config.api_version` as described in the README file.
