### ISSUE TITLE
error with get picture data

### ISSUE THREAD

**Issue by zipi** [arsduo/koala#537]
It's the same for every object when I try to get associated picture data all I get is this error message Koala::Facebook::ClientError: type: OAuthException, code: 12, message: (#12) picture edge for this type is deprecated for versions v2.3 and higher.

What should I be doing to get a photo URL instead of this error?

EDIT:
This is interesting if I change Koala.config.api_version to "v2.2" I can get a URL, but the picture is not what I posted to Facebook, it's just a question mark ?

**Comment by zipi** [comment]
So I just don't know how to use the API. I was able to get what I wanted by adding the fields: "picture" option when I get feeds, never mind.

**Comment by HamzehSoboh** [comment]
Don't you think it's very small? Please provide an alternative. Thanks.
