### ISSUE TITLE
batch request - undefined method `code' for nil:NilClass

### ISSUE THREAD

**Issue by faustoct** [arsduo/koala#539]
It was working fine but stopped suddenly

I tried perform this

```
access_token = RestClient.get("https://graph.facebook.com/oauth/access_token?type=client_cred&client_id=client_id_here&client_secret=secret_id_here")
token = access_token.split("=")[1]
graph = Koala::Facebook::API.new(token)
graph.batch do |batch_api|
batch_api.get_connections("111090485635468", "photos?fields=link,created_time,name,images,source,from&limit=1&type=uploaded")
end
```

Stacktrace

```
NoMethodError: undefined method `code' for nil:NilClass
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:16:in `code'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/rest-client-2.0.0/lib/restclient/response.rb:38:in `inspect'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/koala-2.4.0/lib/koala/http_service.rb:117:in `inspect'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/koala-2.4.0/lib/koala/http_service.rb:117:in `make_request'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/koala-2.4.0/lib/koala.rb:64:in `make_request'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/koala-2.4.0/lib/koala/api.rb:74:in `api'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/koala-2.4.0/lib/koala/api/graph_api.rb:527:in `graph_call'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/koala-2.4.0/lib/koala/api/graph_batch_api.rb:52:in `execute'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/koala-2.4.0/lib/koala/api/graph_api.rb:501:in `batch'
    from (irb):4
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/padrino-core-0.13.2/lib/padrino-core/cli/base.rb:40:in `console'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/gems/padrino-core-0.13.2/bin/padrino:8:in `<top (required)>'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/bin/padrino:22:in `load'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/bin/padrino:22:in `<main>'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/fausto/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'2.2.1 :007 
```

**Comment by faustoct** [comment]
Something going wrong between _koala_ and _restclient_. The raw code works fine:

curl \
    -F 'access_token=token_comes_here' \
    -F 'batch=[{"method":"GET", "relative_url":"111090485635468/photos?fields=link,created_time,name,images,source,from&limit=1&type=uploaded"}]' \
    https://graph.facebook.com

**Comment by Billy4195** [comment]
Hi, 
If you want to get access token for client, 
you need to get code first and use the code to ask for token.

**Comment by faustoct** [comment]
The same code works with raw code and doesn't with koala. Access token is provided in both.
token = access_token.split("=")[1]

**Comment by Billy4195** [comment]
The  "Code" I said is the a string for FB oauth authenrization
You can get the "Code" from 
https://www.facebook.com/dialog/oauth?client_id={app-id}&redirect_uri={redirect-uri}

the redirect url will contain a string for the "Code"

and use the "Code" to get access token 
ex:
https://www.facebook.com/oauth/access_token?client_id={app-id}&redirect_uri={redirect-uri}&client_secret={app-secret}&code={Code}

Hope this will help you

**Comment by arsduo** [comment]
Hmm. This sounds like it could be an issue -- are you still experiencing it? If so, can you provide a (sanitized) example of the raw data you get back from Facebook when you do the curl request?

Thanks! Sorry about the late response.

**Comment by arsduo** [comment]
Since it's been three weeks I'm going to close this, but if you are still having the issue, definitely reopen this or create a new issue with some samples of the raw data you get back from Facebook and I'll look into it. Thanks!
