### ISSUE TITLE
Programming issue?

### ISSUE THREAD

**Issue by arjunmenon** [arsduo/koala#540]
Give me a hint or please correct this approach. 

Getting insights for page posts returning `[]`

This is for the Adidas page
`pp graph.get_object("182162001806727/insights/")`
It only returns fields for country data and nothing for page_impressions or page_engagement, etc. Same with for any other page.

Even though the docs mention that Insights are generated for a post/page with more than 30 likes, but still nothing.

Infact, insights for the first post of Adidas page returns nothing, just empty `[]`
`pp graph.get_object("182162001806727_1189840444372206/insights")`
or
`graph.get_connections('182162001806727_1189840444372206', 'insights/page_impressions_frequency_distribution', period: 'week'`

Even though it has high amount of likes and comments, if you check their feed.

So, what is the correct method or is it even possible or publicly available.

And, for pages, is the page_impression/engagement data available?

I am asking a programming question here, honestly because, your wiki is not that friendly. No two faces!

**Comment by batasrki** [comment]
This isn't a gem problem, this is a Facebook problem. If you try that query in Graph Explorer, you will likely get the same result. It's unclear to whom Facebook allows to see the insights endpoint, because I've seen the same issue for pages that are clearly over 30 likes. You need to take this up with Facebook.

**Comment by Timps** [comment]
Faebook insights permissions are crystal clear.

https://developers.facebook.com/docs/graph-api/reference/v2.7/insights

There are only two publicly available metrics. The rest are confidential to owners of the page.
quote from FB:

> **Permissions**
> 
>     Any valid access token can be used for publicly available metrics (**currently page_fans_country or page_storytellers_by_country**).
>     A user access token with read_insights permission can retrieve metrics for all pages and domains owned by this user.
>     A page access token with read_insights permission can retrieve all metrics for that Page.

**Comment by arjunmenon** [comment]
Sure. Thank you.
