### ISSUE TITLE
Posting to facebook Page

### ISSUE THREAD

**Issue by djpate** [arsduo/koala#541]
I'm trying to setup auto publish to my facebook page on my blog.

I have my facebook app_id, secret and page_id.

I went on the Graph explorer and gave manage_page and publish page permission to my app. I did publish to the page from the explorer by using the app (I think)

But in my code I keep getting 

```
Koala::Facebook::ClientError: type: OAuthException, code: 200, message: (#200) The user hasn't authorized the application to perform this action, x-fb-trace-id: GgCrjv+Oz/g [HTTP 403]
```

I keep reading online to go get an access token from the graph explorer but they expire in a few hours and this need to work as a background task with no user interaction of any sort.

Can we use the app id and secret to generate the right access token?

Here is what my code looks like

```
module Social   
  class Facebook
    def initialize(post)
      @post = post
    end

    def post!
      #return unless Rails.env.production?
      graph.put_connections(config['page_id'],'feed', {message: 'hello1'})
    end

    def graph
      @graph ||= Koala::Facebook::API.new(token)
    end

    def token
      oauth.get_app_access_token
    end

    def oauth
      Koala::Facebook::OAuth.new(config['app_id'], config['app_secret'])
    end

    def config
      Rails.application.config_for(:facebook)
    end
  end 
end
```

Thanks

**Comment by batasrki** [comment]
@djpate did you create an app on Facebook's side? If not, you have to do that first, get the `app_id` and `app_secret` from there and use those to post from your app.

**Comment by arsduo** [comment]
Thanks, @batasrki! I'll close this now — @djpate, if you run into any bugs with the gem, please open an issue and I'll help with that. facebook.stackoverflow.com is a good place to ask general questions about the Facebook API.
