### ISSUE TITLE
Video Thumbnails

### ISSUE THREAD

**Issue by jthomp** [arsduo/koala#543]
Hello! I am having an issue trying to attach a thumbnail when uploading a video with Koala. I get the following error: `type: OAuthException, code: 100, message: (#100) Invalid image format. It should be an image file data.`

```
# Post a video
page_graph.put_video(resources.first, {description: message, thumb: image_file}, page_id)
```

I've tried actually downloading the image I want to use and sending the file itself in the `thumb` parameter, but I still get this error. It doesn't accept a URL either. Just wondering if I'm going about this the wrong way.

Thanks.

**Comment by san** [comment]
Anyone figured this out?

I am running into the same issue. It's not working either by image url or image data. It returns the same error as mentioned by @jthomp. 

According to FB documentation (https://developers.facebook.com/docs/graph-api/reference/video), it should work with image data, but its not.

**Comment by drav96** [comment]
Anyone here ?  I also encountered this problem

**Comment by arsduo** [comment]
Apologies for the late response! 

I've been working on the live test suite, and those image tests there seem to be passing okay with test users. You could potentially compare how you implemented it with those calls. 

Are you able to make it work using the Graph API Explorer? I don't think you can send files with that but you could try with a URL. If it works there but not on Koala, we probably have an issue with the gem. 

Another suggestion: set the Koala logger to debug mode (in the Utils module), and let's see what calls are being made. We can compare that to ones we know work.

**Comment by harishbollina** [comment]
Hello arsduo,

I am trying to do the same thing(Adding thumbnail to video) from Graph API and I am receiving the error msg:  "(#100) Invalid image format. It should be an image file data."
The Images that I am using as source are : 
https://www.facebook.com/images/fb_icon_325x325.png
and another Image which is in my local host. Either way is not working for me. Please help what I am doing wrong here....
Also, please provide any source you have to add thumbnail to a video in FB...Thanks in Advance

**Comment by arsduo** [comment]
Hmm. Sounds like this could be a case for a convenience method. Can you provide the code you're trying to use to post the thumbnail and video?

**Comment by harishbollina** [comment]
Sorry for the delayed response....
I am trying to attach a thumbnail to an existing video in FB.....
I am using graph API to do that...
Can I attach a thumbnail to a video on user wall or its only to a video on user page....?As per API..it is only to a page...but I am trying for user wall
I am using the below url for that...
https://graph.facebook.com/<Video-id>/videos
URL for Thumbnail:
=============(Parameter is 'url')
https://www.facebook.com/images/fb_icon_325x325.png
Please correct and suggest me...

**Comment by twelvelabs** [comment]
I was able to reproduce this via the following:

```ruby
thumbnail_file = open('http://some-domain.com/some-thumbnail.jpg')

api = Koala::Facebook::API.new('some-valid-page-access-token')
api.put_video('http://some-domain.com/some-video-file.mp4', {
  title: 'video with custom thumb',
  thumb: thumbnail_file
})
```

I looked around at the internals of `#put_video` and noticed that if the first arg is **not** a URL, then you assume it's a `File`-ish object and wrap it in `Koala::HTTPService::UploadableIO`. I tried that and it worked just fine:

```ruby
api.put_video('http://some-domain.com/some-video-file.mp4', {
  title: 'video with custom thumb',
  thumb: Koala::HTTPService::UploadableIO.new(thumbnail_file)
})
```

Probably just need to add documentation to the README and/or https://github.com/arsduo/koala/wiki/Uploading-Photos-and-Videos ... though should note that the primary photo/video file in `#put_picture` and `#put_video` is already wrapped for you.

Hope this helps!

**Comment by arpwal** [comment]
Any idea on how this could be solved in general on python? 
I've been trying -- 
`
        with open(image_thumbnail_filename, "rb") as image_file:
            poster_encoded_string = base64.b64encode(image_file.read()).decode("utf-8")
`

with no luck.

**Comment by jonnyclinch** [comment]
still no luck with this issue, someone found a solution?

**Comment by AsifShaafi** [comment]
Has anyone found any solution to this issue? or any workaround? I'm also stuck with the same thing. 😢

**Comment by ylecuyer** [comment]
Could you try wrapping the file with `Koala::HTTPService::UploadableIO.new` as explained in this comment: https://github.com/arsduo/koala/issues/543#issuecomment-298646429

**Comment by AsifShaafi** [comment]
> Could you try wrapping the file with `Koala::HTTPService::UploadableIO.new` as explained in this comment: https://github.com/arsduo/koala/issues/543#issuecomment-298646429

Thanks, but I have changed the workflow now, uploading the thumbnail separately for the video after the video is uploaded.

**Comment by sofienargoubi** [comment]
upload thumbnail using local file 
Nestjs with httpModule

`    
    const form = new FormData(); // import * as FormData from 'form-data';
    const buffer = fs.readFileSync('./thumb.png'); // your path to thumbnail && fs import * as fs from "fs";
    form.append('thumb', buffer , { filename: 'thumb.png' }); // add buffer  and name original of thumbnail 
    form.append('access_token', 'your page access token' ); 
    form.append('file_url', 'your video url'};
    const headers = {
      ...form.getHeaders(),
      "Content-Length": form.getLengthSync()
    };
   this.httpService.post(`https://graph-video.facebook.com/v13.0/${pageId}/videos`,form, { headers } );
` 
- Always Do what you love
