### ISSUE TITLE
Get Facebook profile using Ruby gem Koala not working

### ISSUE THREAD

**Issue by RisingPlay** [arsduo/koala#547]
First i tried this:

class FacebooksController < ApplicationController

require 'koala'

def index

@graph = Koala::Facebook::API.new(current_user.oauth_token)
@profile = @graph.get_object("me")
end

end

Errors: Faraday::SSLError in FacebooksController#index SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol

Then I put file cacert.pem(curl.haxx.se/ca/cacert.pem) in root folder and tried this:

class FacebooksController < ApplicationController

require 'koala'

def index

Koala.http_service.http_options = {
  ssl: { ca_path: Rails.root }
}

@graph = Koala::Facebook::API.new(current_user.oauth_token)
@profile = @graph.get_object("me")
end end

Error: TypeError in FacebooksController#index no implicit conversion of Pathname into String

@profile = @graph.get_object("me")

Please Help me.. Any suggestions are welcome. Thanks in advance.

**Comment by arsduo** [comment]
Hi! The first issue is an SSL problem with your local setup -- [this](https://coderwall.com/p/pzsm5w/how-to-fix-the-openssl-certificate-verify-error-in-ruby-using-rvm) might be useful for that. 

The second problem is, I think, that you're trying to use `Rails.root` (which is a Pathname object) when Koala/Faraday expects a string (to the `pem` file itself). 

I apologize for the late response -- hopefully you've figured this out by now. Unfortunately setting up local SSL isn't something I can help with beyond this; if you're still having issues, I recommend looking on Stackoverflow for similar problems. There are a lot of great solutions.
