### ISSUE TITLE
Posting to your own page on facebook

### ISSUE THREAD

**Issue by Martijnkerr** [arsduo/koala#549]
In my application I want to post to my own apps facebook page every time a post is made.

I have currently set it up correctly using your guide "acting as a page" where I do

 @graph = Koala::Facebook::API.new("generatedacceskey")
pages = @graph.get_connections('me', 'accounts')
(I see that my apps page is the first one)
page_token = pages.first['access_token']
@page_graph = Koala::Facebook::API.new(page_token)
and then I can make connection and post on my pages wall succesfully with
 @page_graph.put_connections("my_app_id", 'feed', :message => "whatever message", link: "https://www.google.com")

Now I have the issue that this access key only is valid for 24 hours and the actions is not based on an authentication of a user.

I actually always need the same user (my own facebook wich is admin of the apps facebook page) and the only changing variables would be the variables that I'm passing in message and the url of the post.

Is there any way to achieve this with Koala that I always authenticate to my own facebook (without me having to click on any buttons) and that the process just authenticates and posts to my page automatically?

**Comment by tokhi** [comment]
You can actually extend the access token from Facebook developers tool, you can extend it up to 2 months, just select your app and then click extend at the bottom of the page.
https://developers.facebook.com/tools/debug/accesstoken/

**Comment by arsduo** [comment]
Thanks @tokhi! Hope that got things worked out.

For these kinds of general API questions, facebook.stackoverflow.com is a great place to ask. If you run into any bugs with the gem, please open an issue and I'll help with that.
