### ISSUE TITLE
Consider dropping support for fully deprecated Ruby versions?

### ISSUE THREAD

**Issue by acuppy** [arsduo/koala#550]
I know that you've committed to supporting back to 1.8.7 and other deprecated versions, but I would imagine that that support is going to impede performance improvements.  Further, support may come at the cost of added complexity.

A couple of suggestions:
- Strive for v3 to drop support to pre-2.0 Ruby.
- Pop support for older version to a secondary shims repo

Sooner or later, I'd imagine that gem dependencies will move on completely: making the migration tough.

**Comment by arsduo** [comment]
Good idea! At this point, I don't think there's much need to hold onto
older Ruby support. Given how relatively stable Facebook's API has been,
older versions of the gem will likely continue to function for a while, and
I'd rather support the majority of users on newer Rubies.

2016-10-18 12:57 GMT-05:00 Adam Cuppy <notifications@github.com>:

**Comment by acuppy** [comment]
Yeah. It's a tough call, but eventually (and potentially now) the weight of
support out weights the value of it.

I'd be happy to help, if needed.

**Comment by arsduo** [comment]
I'm in the process of releasing 3.0 now, and as you suggested have stopped support for pre-2.0. (Looking forward to required keyword arguments once 2.1 is the minimum!)

Would be happy for your help with future work! I definitely want to simplify more of the code the way your pull request does.
