### ISSUE TITLE
Support for multiple FB Apps at the same time?

### ISSUE THREAD

**Issue by ckbhodge** [arsduo/koala#552]
I'm initializing Koala with one FB App's info (app id, secret, callback url) and that is the usual one that I need to use for making graph api calls.

However, I need to occasionally make calls within the same RoR process to the FB graph api for a different FB App.  What's the best way to do this for one-off calls that I need to make for the 2nd FB App?  I thought initializing a new object like this would work, but it still seems to be using the original app info:
`k = Koala::Facebook::API.new(user_fb_token, APP_2_SECRET)`

Ideally, it can support multiple apps at the same time so that I don't have to worry about other calls accidentally using the 2nd app if I re-initialize Koala.

**Comment by ckbhodge** [comment]
@arsduo sorry to bug you!  any suggestions on this?  thanks!

**Comment by pavelbulanov** [comment]
Just in case, it looks like I responded to you at SO
http://stackoverflow.com/questions/40337803/koala-support-for-multiple-fb-apps-at-the-same-time/40432192#40432192

**Comment by ckbhodge** [comment]
Thanks, @pavelbulanov.  I've responded there.  Closing this out.
