### ISSUE TITLE
User request limit reached

### ISSUE THREAD

**Issue by abhishekchaudhary** [arsduo/koala#554]
Hi we are facing this "User request limit reached" issue but if I use the same token on Fb graph exlorer console it works. I already filed an issue on Facebook support and confirmed that everything is fine at their end.

**Comment by mohsalsaleem** [comment]
Have you been making errorful requests prior to the "User request limit reached"? If that's the case, Facebook might be throwing that error. You can make the request again after waiting 5 minutes. That has been the problem in my case.

**Comment by abhishekchaudhary** [comment]
@mohsalsaleem Initially I filed a bug with Facebook only but they are saying everything is working fine at their end.

**Comment by mohsalsaleem** [comment]
I suggest you go through the code and see if you are making any mistakes anywhere which causes an error.

**Comment by abhishekchaudhary** [comment]
@mohsalsaleem I don't think there is any scope for mistake from my side as I am simply calling get_connections method on Koala instance.

**Comment by arsduo** [comment]
Hmm, that's strange. Are you still seeing this issue? If so, can you turn on Koala's debug mode and compare the requests it's making that fail with the ones that work in the explorer? If we can identify the differences we can fix any discrepancy.

**Comment by arsduo** [comment]
Since it's been three weeks I'm going to close this, but if you are still having the issue and can see it working in the Graph Explorer, definitely reopen this or create a new issue with that info and the debug logs. Thanks!
