### ISSUE TITLE
Post Like is not working

### ISSUE THREAD

**Issue by jaypandya73** [arsduo/koala#562]
How i can make post request on users FB posts through application?

I am using below code for making post request:

```
token = user.facebook_auth.token
graph = Koala::Facebook::API.new(token)
```
when i try to make post request through Koala gem 

```
response = graph.put_like(post_id)
```

and error says
```
Koala::Facebook::ClientError: type: OAuthException, code: 3, message: (#3) Publishing likes through the API is only available for page access tokens [HTTP 400]
```

__Note__ - Also i have tried to make call with page_access token but still getting same error.

I have gone through some links for this issues and seems like facebook has made some changes in their policy for liking public pages.(refer below link)

https://developers.facebook.com/bugs/1754734484744033/

Is there anyone who is facing same issue or is there anything that i missed?

Your help is appreciated.

__Note:__ This code was working while ago.

**Comment by danielbonnell** [comment]
Facebook has restricted the ability to `like` a post through the API to pages. You can only like a post if you are acting as a page now. The error message basically says as much. You can read more [here](http://stackoverflow.com/a/41450633/4139179).

**Comment by arsduo** [comment]
Thanks, @danielbonnell! I'm going to close this since it seems like the issue's resolved.
