### ISSUE TITLE
Lots of errors about "GET {photo-id}/feed" when using get_connections("me, "feed") 

### ISSUE THREAD

**Issue by bobber205** [arsduo/koala#563]
Our use of the koala gem is this solo use case, aside from the webhook integration/meet challenge features.
```
get_connections("me", 'feed', {fields: "updated_time,message,created_time,id,link,place,from,attachments,privacy", since: 1.days.ago.utc.to_i})
```

For some reason we get tons of these errors 

![image](https://cloud.githubusercontent.com/assets/5841107/21627781/1a905364-d1cf-11e6-8a0c-79c0d2074687.png)

We've never ever made that call explicitly. Is it possible that the gem is making that call for us? 
We get photo related information if it exists in the attachments field but that seems to be standard me/feed. I get basically all the same info when I use the OpenGraph API explorer on facebook's dev site.

It's causing us a ton of headaches, would be great to have any hint where these calls might be coming from. (FWIW this has been happening for almost a year so I know it's not a temporary error on FB's end)

Thanks! 💃

**Comment by arsduo** [comment]
Apologies for the late response! Koala is a pretty simple gem so it shouldn't be making any extra calls. There's a tiny bit of processing around photos but nothing that looks at /feed to my knowledge.

When you look at the errors in the Facebook alert, what do you see? 

One approach might be to turn on Koala's debug mode and set the logger appropriately to see what calls are getting made. I'd be very interested to see what that shows.

Let me know what you find!

**Comment by bobber205** [comment]
Thanks so much!
I added it and I only see the subs endpoint and /me/feed

Just like I expected!

Again I really appreciate you taking the time to respond :)

Don't worry about it being late. We're all super busy!
