### ISSUE TITLE
Batch API should use Response objects

### ISSUE THREAD

**Issue by arsduo** [arsduo/koala#581]
This will be useful as future work extends the link between GraphCollection and Responses.

**Comment by acuppy** [comment]
How so? I'd be happy to put work into this if you want to guide me down the path.

**Comment by arsduo** [comment]
After sleeping on it, I'm not sure it's actually necessary. The big question was how provide information about the response headers to GraphCollection so users can access etags or rate limits (see #454 or #522). 

It turns out that by clearing up the relationship between API#api and API#graph_call (#584), we can provide that info where it's needed without having to refactor the batch API.

(That said, the batch API doesn't currently offer the option of returning the whole response object the way that the regular API does. There's probably still an argument for creating Response objects while processing the results, even if most of the time they're only internal.)

**Comment by austin-wang** [comment]
This issue is well-timed: I was actually looking for this functionality and started working on this: https://github.com/austin-wang/koala/commit/641ae82f8cc71d983fac9bb59229bfe884624c6e

**Comment by arsduo** [comment]
Awesome @austin-wang! I appreciate that. 

One note: there've been a bunch of Koala changes leading to 3.0 (which should come out soon and which I'd love to include this in). Batch API in particular has been refactored (thanks, @acuppy!). Would you be able to reapply your changes to the new code? It should be a little annoying but not too hard.

**Comment by austin-wang** [comment]
@arsduo will do, I'll take a look at latest on master.

**Comment by arsduo** [comment]
Thanks! Let me know if you have any questions.

(I just added a pull request template as well -- let me know what you think
when you open it up!)

2017-02-22 18:34 GMT-06:00 Austin Wang <notifications@github.com>:

**Comment by arsduo** [comment]
@austin-wang someone just submitted #589, which incorporates these changes. I don't believe it has an option to turn the full response object from the batch API, but I'll add that when I merge it in this week (unless you want to submit a PR based on those changes).

Thanks for your feedback and for using Koala!
