### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by pawandubey** [arsduo/koala#595]
Trying out Koala 3.x with Rails 4.2.7 and it seems like it depends on `json` version `>= 2.0` but `rails` itself locks it as `json (>= 1.7.7, ~> 1.7)`.

So no way to use it with rails 4.2 apps as of now. Maybe drop `json` version to `>= 1.7`?

EDIT: I see that it was done to enable the `quirks_mode` option. Anyway around it?

**Comment by arsduo** [comment]
It wasn't actually necessary to up the JSON version -- 2.0 was supposed to fully support the JSON spec, but in the end I had to use quirks_mode. Since Rails 4 requires an earlier version, that's definitely the way to go -- Koala has to be compatible with Rails 4. Closing this and merging in the PR.
