### ISSUE TITLE
ArgumentError: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by OmarZV** [arsduo/koala#600]
Hi guys,

I was working with Koala gem in combo with Omniauth and devise. I was able to call this command in the console " u.facebook(u).get_object("me")" perfectly with one user two days ago. And now, when I do it for a new user who just signed in a I get an argument error. I have provided my relevant code below and a screenshot. Any help would be amazing - thank you so much!!

**User.rb**
```
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

 def self.from_omniauth(auth)        
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name     
      user.avatar = URI.parse(auth.info.image)
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end
  
  def facebook
    @facebook ||= Koala::Facebook::API.new(self.oauth_token)
  end
```

![screen shot 2017-03-14 at 12 54 29 pm](https://cloud.githubusercontent.com/assets/16312270/23912381/cae813ba-08b5-11e7-8250-e8ac377cc42c.png)

**Comment by arsduo** [comment]
You're calling `u.facebook(u)` but defined the Facebook method to not require any arguments. Remove that and you should stop getting that error.

Good luck and thanks for using 🐨!

**Comment by OmarZV** [comment]
Arsduo thank you so much 😄  if i can bother you with one more quick question. In my rails console when I try calling a user besides last using User.where(id:9) --> I get an undefined facebook for that user. But it worked perfectly when that user was the last one. 

![screen shot 2017-03-14 at 1 05 44 pm](https://cloud.githubusercontent.com/assets/16312270/23912772/2be80bec-08b7-11e7-9114-59710c5d9b52.png)

**Comment by arsduo** [comment]
`User.where` returns an `ActiveRecord::Collection` object, which is more or less an Array for your purposes. You'll either need to call `.first` or use `User.find_by` to return the User object itself. (If you haven't looked at the documentation for ActiveRecord queries, you should -- it's really well written.)

Good luck!

**Comment by OmarZV** [comment]
Thanks Champ!!
