### ISSUE TITLE
Koala::Facebook::ClientError OAuthException in v3.0.0.rc2

### ISSUE THREAD

**Issue by cyurtbil** [arsduo/koala#607]
Hi,

I have just implemented Koala v3.0.0.rc2 to my Heroku hosted Rails application for Facebook Login with Graph API.

I'm getting this error with some of my users:
Koala::Facebook::ClientError (type: OAuthException, code: 5, message: (#5) Unauthorized source IP address, x-fb-trace-id: Dpoe+vZ6aMC [HTTP 400])

Is this a Koala issue> If it is, I would be happy to answer any questions to ease the process of fixing the problem.

Thanks.

**Comment by leonelgalan** [comment]
I don't think so, that error is coming directly from Facebook and it implies that the IP address has been blacklisted (temporarily from my experience). I also host an app on Heroku and we see a Spike of this errors in the last few days.

We believe this is related to Facebook's new efforts on fighting fake accounts. But don't have a confirmation yet.

**Comment by cyurtbil** [comment]
Yes, I have assumed that too, but just would like to make sure it is a Koala issue. Thanks for the quick reply. I am going to close the issue right now.
