### ISSUE TITLE
type: OAuthException, code: 2500, message: Unknown path components:

### ISSUE THREAD

**Issue by MuneebSarfraz94** [arsduo/koala#611]
When i pass parameters to oauth.get_connections() method it returns following error with logs
Koala::Facebook::AuthenticationError: type: OAuthException, code: 2500, message: Unknown path components: /IUPATDC35/feed, x-fb-trace-id: Fdl5cjt9fLC [HTTP 400]
	from /home/munib/.rvm/gems/ruby-2.1.10@unionconnect-rails/gems/koala-2.3.0/lib/koala/api/graph_api.rb:529:in `block in graph_call'
	from /home/munib/.rvm/gems/ruby-2.1.10@unionconnect-rails/gems/koala-2.3.0/lib/koala/api.rb:80:in `api'
	from /home/munib/.rvm/gems/ruby-2.1.10@unionconnect-rails/gems/koala-2.3.0/lib/koala/api/graph_api.rb:527:in `graph_call'
	from /home/munib/.rvm/gems/ruby-2.1.10@unionconnect-rails/gems/koala-2.3.0/lib/koala/api/graph_api.rb:116:in `get_connection'
	from (irb):9
	from /home/munib/.rvm/gems/ruby-2.1.10@unionconnect-rails/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
	from /home/munib/.rvm/gems/ruby-2.1.10@unionconnect-rails/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
	from /home/munib/.rvm/gems/ruby-2.1.10@unionconnect-rails/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

**Comment by jlfenaux** [comment]
I had the same error when I specified a wrong version of the Facebook API. 
Koala.config.api_version = "v2.80"
instead of 
Koala.config.api_version = "v2.8"

**Comment by codener** [comment]
Happened to me with the subtle `Koala.config.api_version = "2.80"` :see_no_evil:

**Comment by MuneebSarfraz94** [comment]
yeah it was same issue with me. Fixed now. thanks for the response though almost after a year :laughing:

**Comment by jlfenaux** [comment]
Leaving a trace on the issue page  may help someone else. ;-)

**Comment by mobcoder-radha** [comment]
I read all ads from one ad account: 
i am hit this api  https://graph.facebook.com/v4.0/act_440553599910864/ads
and pass the access token but this give me 
{
    "error": {
        "message": "An access token is required to request this resource.",
        "type": "OAuthException",
        "code": 104,
        "fbtrace_id": "Ax5oXb5EbXOYJJpkwk16FCO"
    }
}

**Comment by ylecuyer** [comment]
Thanks for your feedback @jlfenaux
