### ISSUE TITLE
getting Posts from public page fails sometimes

### ISSUE THREAD

**Issue by tamaloa** [arsduo/koala#620]
We are currently monitoring public facebook pages.
For very few pages we are not able to retrieve results using Koala. Meanwhile we can retrieve results from the Facebook API-Explorer.

Example:

> curl -i -X GET \
>  "https://graph.facebook.com/v2.10/645760532106194/posts?access_token=REMOVED

works (also with older versions of API)

While

```
> fb_api.class
 => Koala::Facebook::API 
> fb_api.get_connection('645760532106194', 'posts')
Koala::Facebook::ClientError: type: GraphMethodException, code: 100, message: Unsupported get request. Object with ID '645760532106194' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api, x-fb-trace-id: CnGhfrjUYsG [HTTP 400]
	from /home/prilop/.rvm/gems/ruby-2.3.3/gems/koala-3.0.0/lib/koala/api.rb:50:in `graph_call'
```

Results in an error but works for other pages/IDs as below

```
> fb_api.get_connection('464337703775204', 'posts')
 => [{"message"=>"Am Samstagabend wurde die Wiedereinweih....
```

Any Idea what may be causing this?

**Comment by Meekohi** [comment]
https://developers.facebook.com/bugs/316526372199563/

The gist of it is:

> These users registered for Facebook/Messenger using their phone number and such users are not yet queryable by the API. This is on the roadmap for the API, please keep an eye on our changelog for when this goes live in a future version: https://developers.facebook.com/docs/graph-api/changelog"

**Comment by tamaloa** [comment]
Thanks for your feedback. As we can succesfull query using the API-Explorer provided by Facebook i suppose https://developers.facebook.com/bugs/316526372199563/  is not the cause of above issue.

**Comment by ylecuyer** [comment]
Closing as old and stale.
Feel free to open a new issue if you still have troubles with the gem
