### ISSUE TITLE
Rails - Koala / Faraday Gems Execution Expired Error

### ISSUE THREAD

**Issue by jonsrose** [arsduo/koala#625]
0down votefavorite | I am working on a rails application that uses Koala gem (v2.2) and Faraday (0.9.2). It seems like a lot of the facebook requests are erroring out with execution required and Im not sure why. 

here is code snippet:

oauth = Koala::Facebook::OAuth.new(Rails.application.config.facebook_app_id,
                                   Rails.application.config.facebook_app_secret,
                                   nil)

app_access_token = oauth.get_app_access_token # fails here
app_graph = Koala::Facebook::API.new(app_access_token)
token_info = app_graph.debug_token(atoken) # or fails here

Here is a stack trace. I would be grateful on help on how to troubleshoot this issue,ERROR: execution expired /usr/lib/ruby/1.9.2/net/http.rb:644:in initialize'   /usr/lib/ruby/1.9.2/net/http.rb:644:inopen' /usr/lib/ruby/1.9.2/net/http.rb:644:in block in connect'   /usr/lib/ruby/1.9.2/net/http.rb:644:inconnect' /usr/lib/ruby/1.9.2/net/http.rb:637:in do_start'   /usr/lib/ruby/1.9.2/net/http.rb:626:instart' /usr/lib/ruby/1.9.2/net/http.rb:1168:in request'   /usr/lib/ruby/gems/1.9.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:inperform_request' /usr/lib/ruby/gems/1.9.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in block in call'   /usr/lib/ruby/gems/1.9.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:inwith_net_http_connection' /usr/lib/ruby/gems/1.9.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in call'   /usr/lib/ruby/gems/1.9.2/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:incall' /usr/lib/ruby/gems/1.9.2/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in call'   /usr/lib/ruby/gems/1.9.2/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:inbuild_response' /usr/lib/ruby/gems/1.9.2/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in run_request'   /usr/lib/ruby/gems/1.9.2/gems/faraday-0.9.2/lib/faraday/connection.rb:177:inpost' /usr/lib/ruby/gems/1.9.2/gems/koala-2.2.0/lib/koala/http_service.rb:113:in make_request'   /usr/lib/ruby/gems/1.9.2/gems/koala-2.2.0/lib/koala.rb:64:inmake_request' /usr/lib/ruby/gems/1.9.2/gems/koala-2.2.0/lib/koala/oauth.rb:306:in fetch_token_string'   /usr/lib/ruby/gems/1.9.2/gems/koala-2.2.0/lib/koala/oauth.rb:258:inget_token_from_server' /usr/lib/ruby/gems/1.9.2/gems/koala-2.2.0/lib/koala/oauth.rb:189:in get_app_access_token_info'   /usr/lib/ruby/gems/1.9.2/gems/koala-2.2.0/lib/koala/oauth.rb:199:inget_app_access_token'

**Comment by ylecuyer** [comment]
Closing as old and stale.
Feel free to open a new issue if you still have troubles with the gem
