### ISSUE TITLE
Friends returns empty array

### ISSUE THREAD

**Issue by tootis** [arsduo/koala#629]
Hello,

I am using the latest version of Koala (3.0.0)
When I use `Koala::Facebook::API(access_token).get_object("me", fields: "email,friends,...)`

I get `"friends => {"data"=>[], "summary"=>{"total_count"=>312}}"`
I get the right `total_count` but the data array is empty

I've tried to do:
`Koala.config.api_version = "v2.6"`
`Koala.config.api_version = "v2.0"`

But nothing works for me

Can anyone help please?

Thanks in advance

**Comment by rmorcos** [comment]
@tootis make sure your access_token has user_friends permission granted

**Comment by rafaltrojanowski** [comment]
@tootis Solved your problem?

**Comment by tootis** [comment]
No, I had the permission from the very beginning.

**Comment by ylecuyer** [comment]
Closing as old and stale.
Feel free to open a new issue if you still have troubles with the gem
