### ISSUE TITLE
Error window nags

### ISSUE THREAD

**Issue by wrabit** [arsduo/koala#632]
1. It doesn't hang around long enough to always understand the source of the bug before the window disappears. A suggested solution: When mouse is hovered over the box, it remains until mouseout.

2. Long strings are not broken so things like path names are often broken rendering the error a bit unhelpful when you cannot easily see the problematic file.

**Comment by ylecuyer** [comment]
Closing as old and stale.
Feel free to open a new issue if you still have troubles with the gem.
