### ISSUE TITLE
When calling "put_wall_post" funstion of koala, facebook is not picking up the image

### ISSUE THREAD

**Issue by prshntchourasia** [arsduo/koala#633]
When calling the below function, facebook is not picking up the image from picture instead it is picking up the (image, description) from meta tags of the link which is mentioned in the link key, which I dont want in my case.
```
_@api.put_wall_post("Hello there!", {
  "name" => "Link name",
  "link" => "http://www.example.com/",
  "caption" => "{*actor*} posted a new review",
  "description" => "This is a longer description of the attachment",
  "picture" => "http://www.example.com/thumbnail.jpg"
})_
```

**Comment by sn0bored** [comment]
This one snuck up on me as well.  Facebook no longer allows you to set the picture you are sharing for a link.  They removed it last year.

https://developers.facebook.com/blog/post/2017/06/27/API-Change-Log-Modifying-Link-Previews/

You can share the image through the `put_picture` method.  Or you can make you link the url to the image (this one can be ugly though).  But FB will not allow you to share a link and use a different preview image anymore.

**Comment by ylecuyer** [comment]
Thanks for your feedback @sn0bored 
Closing for now
