### ISSUE TITLE
Facebook Graph API v2.5 Deprecated

### ISSUE THREAD

**Issue by cntran** [arsduo/koala#636]
Facebook API v2.5 will be deprecated on April 12th, 2018:
https://developers.facebook.com/docs/graph-api/changelog

Is Koala going to be compatible once deprecation occurs?

**Comment by arsduo** [comment]
It will. Koala doesn't implement any particular version of the API. Let me know if you run into any issues with the library itself at the cutover!

**Comment by cntran** [comment]
Ok thanks much!
