### ISSUE TITLE
Getting page posts returns an empty array

### ISSUE THREAD

**Issue by ayunker** [arsduo/koala#638]
Hi - 
We've been using Koala to get posts from our facebook page using `@graph.get_object "#{page_id}/posts"`. This has been working with no issue up through April 24th, since then it returns an empty array.

Making the same call from the Graph API explorer returns the expected posts, and making similar calls using Koala for `@graph.get_object "#{page_id}/photos"` and `@graph.get_object "#{page_id}/feed"` returns data as expected. Only `@graph.get_object "#{page_id}/posts"` returns an empty array.

Has anyone else run into this?

Thanks!

**Comment by mfrederickson** [comment]
My stuff was working fine too until recently, now I am getting:
```
type: GraphMethodException, code: 100, error_subcode: 33, message: Unsupported get request. Object with ID '942018915...redacted' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api, x-fb-trace-id: BOTN...redacted/C [HTTP 400]
```
when I try to get_connections for posts, feeds, etc.  

I think it has to do with [breaking changes](https://developers.facebook.com/docs/graph-api/changelog/breaking-changes), and/or requiring my application to be [approved](https://developers.facebook.com/docs/apps/review/)... so I'm looking into that...

**Comment by ayunker** [comment]
This was related to breaking changes, once our app was approved data started flowing again.
