### ISSUE TITLE
Page Access Token Error?

### ISSUE THREAD

**Issue by tekram** [arsduo/koala#639]
user_graph.get_page_access_token(user_token)

The above command used to work just fine but now gives me the error below from FB: 

Koala::Facebook::ClientError: type: OAuthException, code: 10, message: (#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review., x-fb-trace-id: AEuPtmLPH7m [HTTP 400]
        from (irb):9

I am not sure if this is an error on my end but this error started popping up.

**Comment by neeaagh** [comment]
We had this happen to our app yesterday as well. It seems like for Page access we need to submit our app for review. Strange that they just turned it off without notice after we've been using that access for the last two years. I submitted for review yesterday and haven't heard anything back yet.

**Comment by tekram** [comment]
One way around it is using the below which gives you the page access tokens for each page. 

user_graph.get_connections('me','accounts')

**Comment by tekram** [comment]
According to Facebook docs, it does not seem like one should need Page Public Content Access?

https://developers.facebook.com/docs/facebook-login/permissions/v3.0#reference-manage_pages

**Comment by tekram** [comment]
@neeaagh Did you hear back?

**Comment by ylecuyer** [comment]
Closing for now as this was related to a Facebook API change.
