### ISSUE TITLE
Hellpp

### ISSUE THREAD

**Issue by tonito1101** [arsduo/koala#645]
I dont know how to configure the koala someone can help me?

**Comment by luisk182** [comment]
I need help too, anyone?

**Comment by khanimdad** [comment]
You just need to configure yml file and settings on FB and you are done

**Comment by ylecuyer** [comment]
You'll find how to configure koala here: https://github.com/arsduo/koala#configuration
You can also read the Facebook reference documentation: https://developers.facebook.com/docs/graph-api/using-graph-api
