### ISSUE TITLE
Undefined Method "alias_method_chain"

### ISSUE THREAD

**Issue by lonny** [arsduo/koala#646]
Simply trying to load Rails console (Ruby 2.6.0, Rails 5.2.2, koala 3.0.0) gives this error:

config/initializers/koala.rb:26:in `block in <top (required)>': undefined method `alias_method_chain' for Koala::Facebook::OAuth:Class (NoMethodError)

Here is the traceback:

Traceback (most recent call last):
	48: from bin/rails:4:in `<main>'
	47: from bin/rails:4:in `require'
	46: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>'
	45: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
	44: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
	43: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	42: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	41: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	40: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/console/console_command.rb:95:in `perform'
	39: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/command/actions.rb:18:in `require_application_and_environment!'
	38: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
	37: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	36: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	35: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	34: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	33: from /Users/lonny/rails/pn/config/environment.rb:48:in `<top (required)>'
	32: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
	31: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	30: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	29: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	28: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	27: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
	26: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
	25: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	24: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
	23: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:415:in `call'
	22: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	21: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
	20: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	19: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	18: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	17: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	16: from /Users/lonny/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	15: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	14: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
	13: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	12: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
	11: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
	10: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	 9: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
	 8: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
	 7: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
	 6: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
	 5: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	 4: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
	 3: from /Users/lonny/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
	 2: from /Users/lonny/rails/pn/config/initializers/koala.rb:15:in `<top (required)>'
	 1: from /Users/lonny/rails/pn/config/initializers/koala.rb:15:in `class_eval'
/Users/lonny/rails/pn/config/initializers/koala.rb:26:in `block in <top (required)>': undefined method `alias_method_chain' for Koala::Facebook::OAuth:Class (NoMethodError)

**Comment by ylecuyer** [comment]
Hello @lonny, as far as I can see there is no reference to `alias_method_chain` in the project.
From you stacktrace I see this error comes from your initializer which may contain some monkey patch.

I'll close the issue for now, feel free to reopen if you still have the issue.
