### ISSUE TITLE
Graph API v2.8 is going to be Deprecated on Apr 18, 2019.

### ISSUE THREAD

**Issue by Rajesh1213** [arsduo/koala#647]
There is a breaking change in facebook Graph API untill version 2.8, 

`Reminder:` Graph API v2.8 will be deprecated on Apr 18, 2019. Please use the API Upgrade Tool to understand how this might impact your app. For more details see the changelog.

I am using the koala version 1.11.1, Should I update/upgrade anything in my code base before 18 Apr?

**Comment by arsduo** [comment]
You shouldn't need to change anything with Koala! But there might be calls you make with Koala that you'll need to change to reference different endpoints or to reflect other changes. Facebook now has an API upgrade tool that can give you feedback on what will need to change for your app — I'd recommend checking that.

Good luck with the upgrade!

**Comment by Rajesh1213** [comment]
Sure, Thanks a lot @arsduo
