### ISSUE TITLE
NoMethodError (undefined method `scheme' for "https://graph.facebook.com":String):

### ISSUE THREAD

**Issue by khanimdad** [arsduo/koala#657]
Not sure what this issue is all about

**Comment by ylecuyer** [comment]
Hello, there is not enough info to be able to help you. Could you follow the instructions given (template) when you create a new issue? For example, a code example and a stacktrace would help replicate / investigate the issue.

**Comment by khanimdad** [comment]
Its fixed now it was something related to String method extension
