### ISSUE TITLE
please update the graph_collection, the next_page & previous_page are not working

### ISSUE THREAD

**Issue by 1997roylee** [arsduo/koala#658]
def next_page_params
          @paging && @paging["next"] ? parse_page_url(@paging["next"]) : nil
end

def previous_page_params
          @paging && @paging["previous"] ? parse_page_url(@paging["previous"]) : nil
end

these two methods are not supported now!!!
please update it, thanks

**Comment by ylecuyer** [comment]
> please update it, thanks

You are welcome to open a PR

> these two methods are not supported now!!!

Could you give more details? Do you have a repro session we could use? which endpoint/api version?

**Comment by ylecuyer** [comment]
Closing because of the lack of details + no other reports
