### ISSUE TITLE
Facing Koala::Facebook::OAuthTokenRequestError when fetching app_access_token

### ISSUE THREAD

**Issue by jenipharachel** [arsduo/koala#677]
- [x] This is a Koala bug/issue/documentation problem.

_For code issues:_

- [x] I'm using the newest version
- [x] Here's code to replicate the issue:

```
   @oauth = Koala::Facebook::OAuth.new()
    app_access_token = @oauth.get_app_access_token // getting issue here

    @graph = Koala::Facebook::API.new(params[:access_token], app_access_token)
    profile = @graph.get_object("me")
```

I have configured Koala with the secret key and app_id in the koala.rb file under config folder.

I want to use Koala to get the profile details of a user whose access token is obtained from https://github.com/thebergamo/react-native-fbsdk-next in mobile app side and want to create a new user/ login the user based on the details fetched with this access token.

**Comment by ylecuyer** [comment]
What is the issue ?

**Comment by ylecuyer** [comment]
I have just tested getting an app access token and it works as expected

Please provide the full error log, this is most likely a configuration error and the issue will be closed as such
