### ISSUE TITLE
Extra maintainership

### ISSUE THREAD

**Issue by zenspider** [arsduo/koala#690]
Is there anything I (or zendesk) can do to help out?

**Comment by ylecuyer** [comment]
Hello, thanks for the proposal. I think we are good for now, the activity on the project is low as it is mature and fb API is pretty stable.

**Comment by arsduo** [comment]
Hi Ryan, thank you so much for reaching out (and sorry for the late reply -- it's been a busy month!). It's exciting to hear that Zendesk is using Koala :) 

As @ylecuyer said, the API is pretty stable and the project hasn't had a lot of activity recently, so we are good for the current level of maintenance.

That said, if there are specific changes, maintenance needs, or other project needs that you've identified using Koala at Zendesk, we'd love to hear about them! It's entirely possible there are issues we're not really aware of that could make the gem better or more useful to the community. How has your team's experience been? What has been on your mind?
