### ISSUE TITLE
Tagging incorrect?

### ISSUE THREAD

**Issue by zenspider** [arsduo/koala#692]
It looks like you merged and released 3.6.0 today! Thank you!

Unfortunately, it looks like you tagged today's release as 3.5.0, but that was released back in August 2023. You should prolly force push 3.5.0 back to whatever SHA is appropriate (I'll look in a sec) and push 3.6.0 against today's release

**Comment by zenspider** [comment]
NOPE! I'm wrong. You pushed the 3.5.0 tag today but it is correctly pointing at your 3.5.0 bump commit. So disregard that part... Still need to push a 3.6.0 tag for today's release tho. This will help with the "View differences" feature of rubygems.org

**Comment by ylecuyer** [comment]
> Still need to push a 3.6.0 tag for today's release tho.
done
