### ISSUE TITLE
Error Code #31 not raising Koala::Facebook::APIError

### ISSUE THREAD

**Issue by maxmir20** [arsduo/koala#695]
Hello!

We've have a rescue in our code for Koala::Facebook::APIErrors and we've noticed that when error code #31 is returned, it gets passed into our response instead of raising a Koala::Facebook::ClientError

<img width="1510" alt="Screenshot 2024-12-04 at 12 03 48" src="https://github.com/user-attachments/assets/87bb4003-ff4e-4f7e-8c6f-7e1110af7a1a">

When a similar error code is returned #131037, then Koala returns a Koala::Facebook::ClientError

<img width="1512" alt="Screenshot 2024-12-04 at 12 05 06" src="https://github.com/user-attachments/assets/f3cbe7e4-e303-496e-ad95-3a53cb306fde">

Could this be resolved when someone gets a second?

**Comment by ylecuyer** [comment]
Hello @maxmir20, would you be able to share the http status code returned when you have error 31 ? as per https://github.com/arsduo/koala/blob/master/lib/koala/api.rb#L51 and https://github.com/arsduo/koala/blob/master/lib/koala/api/graph_error_checker.rb#L23 it looks like fb is returning 200 in spite of the error

**Comment by maxmir20** [comment]
Unfortunately, we aren't able to get error 31 for that particular user anymore, instead we're now getting a #131037 error code instead, which is returning a 400 and raising the correct error.

If we run into it again, I can provide an update here, but it does appear that the response would probably be 200.

Do you think there should be an edge case check in graph_error_checker for this in this instance?

**Comment by ylecuyer** [comment]
> Do you think there should be an edge case check in graph_error_checker for this in this instance?

No I'd prefer to close the issue for now and wait for extra info if you have it again.

Problem is that fb/graphql is known to return 200 on errors from time to time from what we see with prod load, and starting adding an exception here would mean keeping adding more and more exceptions in the future and they will be hard to maintain
